var searchData=
[
  ['keyedsharedpool',['KeyedSharedPool',['../class_microsoft_1_1_psi_1_1_keyed_shared_pool.html',1,'Microsoft.Psi.KeyedSharedPool&lt; T, TKey &gt;'],['../class_microsoft_1_1_psi_1_1_keyed_shared_pool.html#ac98a77c70d566e07c8077aefb0034b61',1,'Microsoft.Psi.KeyedSharedPool.KeyedSharedPool()']]],
  ['keyedsharedpool_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aimage_2c_28int_2c_20int_2c_20pixelformat_29_3e',['KeyedSharedPool&lt; Microsoft::Psi::Imaging::Image,(int, int, PixelFormat)&gt;',['../class_microsoft_1_1_psi_1_1_keyed_shared_pool.html',1,'Microsoft::Psi']]],
  ['keyedsharedpool_3c_20t_5b_5d_2c_20int_20_3e',['KeyedSharedPool&lt; T[], int &gt;',['../class_microsoft_1_1_psi_1_1_keyed_shared_pool.html',1,'Microsoft::Psi']]],
  ['kind',['Kind',['../class_microsoft_1_1_psi_1_1_metadata.html#ab1e8b5d3f9aeefb3f09298af8f9ef112',1,'Microsoft.Psi.Metadata.Kind()'],['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_1_1_pipeline_element_diagnostics.html#a2ebc8d4b3bf1055f32c164f6d9bee325',1,'Microsoft.Psi.Diagnostics.PipelineDiagnostics.PipelineElementDiagnostics.Kind()']]],
  ['kinectaudiobeaminfo',['KinectAudioBeamInfo',['../struct_microsoft_1_1_psi_1_1_kinect_1_1_kinect_audio_beam_info.html',1,'Microsoft.Psi.Kinect.KinectAudioBeamInfo'],['../struct_microsoft_1_1_psi_1_1_kinect_1_1_kinect_audio_beam_info.html#ad5e9b223e924e3029b24e48f1b38ea01',1,'Microsoft.Psi.Kinect.KinectAudioBeamInfo.KinectAudioBeamInfo()']]],
  ['kinectbodies3dvisualizationobjectconfiguration',['KinectBodies3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_kinect_bodies3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['kinectbody',['KinectBody',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_body.html',1,'Microsoft::Psi::Kinect']]],
  ['kinectcalibration',['KinectCalibration',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_calibration.html',1,'Microsoft.Psi.Kinect.KinectCalibration'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_calibration.html#ad62176ebf2726fdbcbac0cf041b309dc',1,'Microsoft.Psi.Kinect.KinectCalibration.KinectCalibration()'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_calibration.html#a65542eef0878ec131cfbca56a14bd8de',1,'Microsoft.Psi.Kinect.KinectCalibration.KinectCalibration(int colorWidth, int colorHeight, Matrix&lt; double &gt; colorTransform, double colorRadial0, double colorRadial1, double colorTangential0, double colorTangential1, Matrix&lt; double &gt; depthToColorTransform, int depthWidth, int depthHeight, Matrix&lt; double &gt; depthTransform, double depthRadial0, double depthRadial1, double depthTangential0, double depthTangential1)']]],
  ['kinectdepth3dvisualizationobjectconfiguration',['KinectDepth3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_kinect_depth3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['kinectdevice',['KinectDevice',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html#a58f65c05710a1d4113aa5cdc425b9b05',1,'Microsoft::Psi::Kinect::KinectSensor']]],
  ['kinectextensions',['KinectExtensions',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_extensions.html',1,'Microsoft::Psi::Kinect']]],
  ['kinectface',['KinectFace',['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['kinectfacedetector',['KinectFaceDetector',['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face_detector.html',1,'Microsoft.Psi.Kinect.Face.KinectFaceDetector'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face_detector.html#a697169effca5b38d7e4008737277124b',1,'Microsoft.Psi.Kinect.Face.KinectFaceDetector.KinectFaceDetector()']]],
  ['kinectfacedetectorconfiguration',['KinectFaceDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face_detector_configuration.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['kinectsensor',['KinectSensor',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html',1,'Microsoft.Psi.Kinect.KinectSensor'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html#a691e30dd4147d58ff2c75e0bdf9a1dd2',1,'Microsoft.Psi.Kinect.KinectSensor.KinectSensor(Pipeline pipeline, string configurationFilename)'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html#a165b2c0cca8d78e33f157d3bafd8de69',1,'Microsoft.Psi.Kinect.KinectSensor.KinectSensor(Pipeline pipeline, KinectSensorConfiguration configuration)']]],
  ['kinectsensorconfiguration',['KinectSensorConfiguration',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor_configuration.html',1,'Microsoft::Psi::Kinect']]],
  ['knownserializers',['KnownSerializers',['../class_microsoft_1_1_psi_1_1_serialization_1_1_known_serializers.html',1,'Microsoft::Psi::Serialization']]],
  ['knownserializers_3f_3f',['KnownSerializers??',['../class_microsoft_1_1_psi_1_1_serialization_1_1_known_serializers.html#ab19272ffd76de8277c2a6dcf06667a1f',1,'Microsoft::Psi::Serialization::KnownSerializers']]]
];
