var searchData=
[
  ['keyedsharedpool',['KeyedSharedPool',['../class_microsoft_1_1_psi_1_1_keyed_shared_pool.html',1,'Microsoft::Psi']]],
  ['kind',['Kind',['../class_microsoft_1_1_psi_1_1_metadata.html#ab1e8b5d3f9aeefb3f09298af8f9ef112',1,'Microsoft::Psi::Metadata']]],
  ['kinectaudiobeaminfo',['KinectAudioBeamInfo',['../struct_microsoft_1_1_psi_1_1_kinect_1_1_kinect_audio_beam_info.html',1,'Microsoft.Psi.Kinect.KinectAudioBeamInfo'],['../struct_microsoft_1_1_psi_1_1_kinect_1_1_kinect_audio_beam_info.html#ad5e9b223e924e3029b24e48f1b38ea01',1,'Microsoft.Psi.Kinect.KinectAudioBeamInfo.KinectAudioBeamInfo()']]],
  ['kinectbodies3dvisualizationobject',['KinectBodies3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_client_1_1_kinect_bodies3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::Client']]],
  ['kinectbodies3dvisualizationobjectconfiguration',['KinectBodies3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_kinect_bodies3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['kinectbody',['KinectBody',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_body.html',1,'Microsoft::Psi::Kinect']]],
  ['kinectcalibration',['KinectCalibration',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_calibration.html',1,'Microsoft.Psi.Kinect.KinectCalibration'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_calibration.html#ad62176ebf2726fdbcbac0cf041b309dc',1,'Microsoft.Psi.Kinect.KinectCalibration.KinectCalibration()'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_calibration.html#a65542eef0878ec131cfbca56a14bd8de',1,'Microsoft.Psi.Kinect.KinectCalibration.KinectCalibration(int colorWidth, int colorHeight, Matrix&lt; double &gt; colorTransform, double colorRadial0, double colorRadial1, double colorTangential0, double colorTangential1, Matrix&lt; double &gt; depthToColorTransform, int depthWidth, int depthHeight, Matrix&lt; double &gt; depthTransform, double depthRadial0, double depthRadial1, double depthTangential0, double depthTangential1)']]],
  ['kinectdepth3dvisualizationobjectconfiguration',['KinectDepth3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_kinect_depth3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['kinectdevice',['KinectDevice',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html#a58f65c05710a1d4113aa5cdc425b9b05',1,'Microsoft::Psi::Kinect::KinectSensor']]],
  ['kinectextensions',['KinectExtensions',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_extensions.html',1,'Microsoft::Psi::Kinect']]],
  ['kinectface',['KinectFace',['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['kinectfacedetector',['KinectFaceDetector',['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face_detector.html',1,'Microsoft.Psi.Kinect.Face.KinectFaceDetector'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face_detector.html#a3009d5262f7f5163f6f0be3e709ad8f9',1,'Microsoft.Psi.Kinect.Face.KinectFaceDetector.KinectFaceDetector()']]],
  ['kinectfacedetectorconfiguration',['KinectFaceDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_kinect_face_detector_configuration.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['kinectsensor',['KinectSensor',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html',1,'Microsoft.Psi.Kinect.KinectSensor'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html#a691e30dd4147d58ff2c75e0bdf9a1dd2',1,'Microsoft.Psi.Kinect.KinectSensor.KinectSensor(Pipeline pipeline, string configurationFilename)'],['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor.html#a165b2c0cca8d78e33f157d3bafd8de69',1,'Microsoft.Psi.Kinect.KinectSensor.KinectSensor(Pipeline pipeline, KinectSensorConfiguration configuration)']]],
  ['kinectsensorconfiguration',['KinectSensorConfiguration',['../class_microsoft_1_1_psi_1_1_kinect_1_1_kinect_sensor_configuration.html',1,'Microsoft::Psi::Kinect']]],
  ['knownserializers',['KnownSerializers',['../class_microsoft_1_1_psi_1_1_serialization_1_1_known_serializers.html',1,'Microsoft.Psi.Serialization.KnownSerializers'],['../class_microsoft_1_1_psi_1_1_serialization_1_1_known_serializers.html#a825a3d794aff7d30fb365bf42e226a03',1,'Microsoft.Psi.Serialization.KnownSerializers.KnownSerializers()']]]
];
