var searchData=
[
  ['range',['Range',['../struct_microsoft_1_1_psi_1_1_arrays_1_1_range.html',1,'Microsoft::Psi::Arrays']]],
  ['realinterval',['RealInterval',['../class_microsoft_1_1_psi_1_1_real_interval.html',1,'Microsoft::Psi']]],
  ['realsensedevice',['RealSenseDevice',['../class_microsoft_1_1_psi_1_1_real_sense_1_1_windows_1_1_real_sense_device.html',1,'Microsoft::Psi::RealSense::Windows']]],
  ['realsensedeviceunmanaged',['RealSenseDeviceUnmanaged',['../class_real_sense_device_unmanaged.html',1,'']]],
  ['realsensesensor',['RealSenseSensor',['../class_microsoft_1_1_psi_1_1_real_sense_1_1_windows_1_1_real_sense_sensor.html',1,'Microsoft::Psi::RealSense::Windows']]],
  ['receiver',['Receiver',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20bool_20_3e',['Receiver&lt; bool &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20dictionary_3c_20tkey_2c_20tin_20_3e_20_3e',['Receiver&lt; Dictionary&lt; TKey, TIn &gt; &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20int_20_3e',['Receiver&lt; int &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e',['Receiver&lt; Microsoft::Psi::Audio::AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20jtoken_20_3e_20_3e',['Receiver&lt; Microsoft::Psi::Message&lt; JToken &gt; &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20microsoft_3a_3apsi_3a_3acommon_3a_3abufferreader_20_3e_20_3e',['Receiver&lt; Microsoft::Psi::Message&lt; Microsoft::Psi::Common::BufferReader &gt; &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3ashared_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aimage_20_3e_20_3e',['Receiver&lt; Microsoft::Psi::Shared&lt; Microsoft::Psi::Imaging::Image &gt; &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tclock_20_3e',['Receiver&lt; TClock &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tin_20_3e',['Receiver&lt; TIn &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tin_5b_5d_3e',['Receiver&lt; TIn[]&gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tsecondary_20_3e',['Receiver&lt; TSecondary &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['recognitionresult',['RecognitionResult',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_recognition_result.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['recognizedphrase',['RecognizedPhrase',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_recognized_phrase.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['recyclingpool',['RecyclingPool',['../class_microsoft_1_1_psi_1_1_recycling_pool.html',1,'Microsoft::Psi']]],
  ['referencecountedobject',['ReferenceCountedObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_server_1_1_reference_counted_object.html',1,'Microsoft::Psi::Visualization::Server']]],
  ['relativepathconverter',['RelativePathConverter',['../class_microsoft_1_1_psi_1_1_data_1_1_converters_1_1_relative_path_converter.html',1,'Microsoft::Psi::Data::Converters']]],
  ['relativetimeinterval',['RelativeTimeInterval',['../class_microsoft_1_1_psi_1_1_relative_time_interval.html',1,'Microsoft::Psi']]],
  ['remoteexporter',['RemoteExporter',['../class_microsoft_1_1_psi_1_1_remoting_1_1_remote_exporter.html',1,'Microsoft::Psi::Remoting']]],
  ['remoteimporter',['RemoteImporter',['../class_microsoft_1_1_psi_1_1_remoting_1_1_remote_importer.html',1,'Microsoft::Psi::Remoting']]],
  ['repeater',['Repeater',['../class_microsoft_1_1_psi_1_1_components_1_1_repeater.html',1,'Microsoft::Psi::Components']]],
  ['replaydescriptor',['ReplayDescriptor',['../class_microsoft_1_1_psi_1_1_replay_descriptor.html',1,'Microsoft::Psi']]],
  ['resources',['Resources',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_resources.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rgbcameracollection',['RGBCameraCollection',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_r_g_b_camera_collection.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rgbcameraenumerator',['RGBCameraEnumerator',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_r_g_b_camera_enumerator.html',1,'Microsoft::Psi::Media_Interop']]],
  ['runtimeinfo',['RuntimeInfo',['../class_microsoft_1_1_psi_1_1_common_1_1_runtime_info.html',1,'Microsoft::Psi::Common']]]
];
