var searchData=
[
  ['range_3407',['Range',['../struct_microsoft_1_1_psi_1_1_arrays_1_1_range.html',1,'Microsoft::Psi::Arrays']]],
  ['rangesummarizer_3408',['RangeSummarizer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_summarizers_1_1_range_summarizer.html',1,'Microsoft::Psi::Visualization::Summarizers']]],
  ['readrequest_3409',['ReadRequest',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_read_request.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['realinterval_3410',['RealInterval',['../class_microsoft_1_1_psi_1_1_real_interval.html',1,'Microsoft::Psi']]],
  ['realsensedevice_3411',['RealSenseDevice',['../class_microsoft_1_1_psi_1_1_real_sense_1_1_windows_1_1_real_sense_device.html',1,'Microsoft::Psi::RealSense::Windows']]],
  ['realsensedeviceunmanaged_3412',['RealSenseDeviceUnmanaged',['../class_real_sense_device_unmanaged.html',1,'']]],
  ['realsensesensor_3413',['RealSenseSensor',['../class_microsoft_1_1_psi_1_1_real_sense_1_1_windows_1_1_real_sense_sensor.html',1,'Microsoft::Psi::RealSense::Windows']]],
  ['receiver_3414',['Receiver',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20bool_20_3e_3415',['Receiver&lt; bool &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20int_20_3e_3416',['Receiver&lt; int &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e_3417',['Receiver&lt; Microsoft::Psi::Audio::AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3ashared_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aimage_20_3e_20_3e_3418',['Receiver&lt; Microsoft::Psi::Shared&lt; Microsoft::Psi::Imaging::Image &gt; &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tin_20_3e_3419',['Receiver&lt; TIn &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tin_5b_5d_3e_3420',['Receiver&lt; TIn[]&gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tsecondary_20_3e_3421',['Receiver&lt; TSecondary &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receivercollector_3422',['ReceiverCollector',['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_diagnostics_collector_1_1_receiver_collector.html',1,'Microsoft::Psi::Diagnostics::DiagnosticsCollector']]],
  ['receiverdiagnostics_3423',['ReceiverDiagnostics',['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_internal_1_1_receiver_diagnostics.html',1,'Microsoft.Psi.Diagnostics.PipelineDiagnosticsInternal.ReceiverDiagnostics'],['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_1_1_receiver_diagnostics.html',1,'Microsoft.Psi.Diagnostics.PipelineDiagnostics.ReceiverDiagnostics']]],
  ['recognitionresult_3424',['RecognitionResult',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_recognition_result.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['recognizedphrase_3425',['RecognizedPhrase',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_recognized_phrase.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['rect3dlistvisualizationobject_3426',['Rect3DListVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_rect3_d_list_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['rect3dvisualizationobject_3427',['Rect3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_rect3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['recyclingpool_3428',['RecyclingPool',['../class_microsoft_1_1_psi_1_1_recycling_pool.html',1,'Microsoft::Psi']]],
  ['reframe_3429',['Reframe',['../class_microsoft_1_1_psi_1_1_audio_1_1_reframe.html',1,'Microsoft::Psi::Audio']]],
  ['relativeindexwindow_3430',['RelativeIndexWindow',['../class_microsoft_1_1_psi_1_1_components_1_1_relative_index_window.html',1,'Microsoft::Psi::Components']]],
  ['relativepathconverter_3431',['RelativePathConverter',['../class_microsoft_1_1_psi_1_1_data_1_1_converters_1_1_relative_path_converter.html',1,'Microsoft::Psi::Data::Converters']]],
  ['relativetimeinterval_3432',['RelativeTimeInterval',['../class_microsoft_1_1_psi_1_1_relative_time_interval.html',1,'Microsoft::Psi']]],
  ['relativetimewindow_3433',['RelativeTimeWindow',['../class_microsoft_1_1_psi_1_1_components_1_1_relative_time_window.html',1,'Microsoft::Psi::Components']]],
  ['remoteexporter_3434',['RemoteExporter',['../class_microsoft_1_1_psi_1_1_remoting_1_1_remote_exporter.html',1,'Microsoft::Psi::Remoting']]],
  ['remoteimporter_3435',['RemoteImporter',['../class_microsoft_1_1_psi_1_1_remoting_1_1_remote_importer.html',1,'Microsoft::Psi::Remoting']]],
  ['replaydescriptor_3436',['ReplayDescriptor',['../class_microsoft_1_1_psi_1_1_replay_descriptor.html',1,'Microsoft::Psi']]],
  ['reproducible_3437',['Reproducible',['../class_microsoft_1_1_psi_1_1_reproducible.html',1,'Microsoft::Psi']]],
  ['reproducibleinterpolator_3438',['ReproducibleInterpolator',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft.Psi.ReproducibleInterpolator&lt; T &gt;'],['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft.Psi.ReproducibleInterpolator&lt; TIn, TResult &gt;']]],
  ['reproducibleinterpolator_3c_20t_20_3e_3439',['ReproducibleInterpolator&lt; T &gt;',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft::Psi']]],
  ['reproducibleinterpolator_3c_20t_2c_20t_20_3e_3440',['ReproducibleInterpolator&lt; T, T &gt;',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft::Psi']]],
  ['reproducibleinterpolator_3c_20tin_2c_20tout_20_3e_3441',['ReproducibleInterpolator&lt; TIn, TOut &gt;',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft::Psi']]],
  ['resources_3442',['Resources',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_resources.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rgbcameracollection_3443',['RGBCameraCollection',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_r_g_b_camera_collection.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rgbcameraenumerator_3444',['RGBCameraEnumerator',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_r_g_b_camera_enumerator.html',1,'Microsoft::Psi::Media_Interop']]],
  ['runtimeinfo_3445',['RuntimeInfo',['../class_microsoft_1_1_psi_1_1_common_1_1_runtime_info.html',1,'Microsoft::Psi::Common']]]
];
