var searchData=
[
  ['pair',['Pair',['../class_microsoft_1_1_psi_1_1_components_1_1_pair.html',1,'Microsoft::Psi::Components']]],
  ['parallel',['Parallel',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel.html',1,'Microsoft::Psi::Components']]],
  ['parallelsparse',['ParallelSparse',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel_sparse.html',1,'Microsoft::Psi::Components']]],
  ['partialspeechresponseeventargs',['PartialSpeechResponseEventArgs',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_partial_speech_response_event_args.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['partitionbase',['PartitionBase',['../class_microsoft_1_1_psi_1_1_extensions_1_1_data_1_1_partition_base.html',1,'Microsoft::Psi::Extensions::Data']]],
  ['passthroughconverter',['PassThroughConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_pass_through_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['perfcountercollection',['PerfCounterCollection',['../class_microsoft_1_1_psi_1_1_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['perfcounters',['PerfCounters',['../class_microsoft_1_1_psi_1_1_perf_counters.html',1,'Microsoft::Psi']]],
  ['phonemereachedeventdata',['PhonemeReachedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_phoneme_reached_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['pieslicearrowsvisual3d',['PieSliceArrowsVisual3D',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals3_d_1_1_pie_slice_arrows_visual3_d.html',1,'Microsoft::Psi::Visualization::Views::Visuals3D']]],
  ['pipeline',['Pipeline',['../class_microsoft_1_1_psi_1_1_pipeline.html',1,'Microsoft::Psi']]],
  ['pipelinecompletioneventargs',['PipelineCompletionEventArgs',['../class_microsoft_1_1_psi_1_1_pipeline_completion_event_args.html',1,'Microsoft::Psi']]],
  ['pixelformat',['PixelFormat',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_internal_1_1_pixel_format.html',1,'Microsoft::Psi::Media::MediaCaptureInternal']]],
  ['pixelformatextensions',['PixelFormatExtensions',['../class_microsoft_1_1_psi_1_1_imaging_1_1_pixel_format_extensions.html',1,'Microsoft::Psi::Imaging']]],
  ['pixelformathelper',['PixelFormatHelper',['../class_microsoft_1_1_psi_1_1_imaging_1_1_pixel_format_helper.html',1,'Microsoft::Psi::Imaging']]],
  ['placementconverter',['PlacementConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_placement_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['plotvisualizationobject',['PlotVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_client_1_1_plot_visualization_object.html',1,'Microsoft.Psi.Visualization.Client.PlotVisualizationObject'],['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft.Psi.Visualization.VisualizationObjects.PlotVisualizationObject'],['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft.Psi.Visualization.VisualizationObjects.PlotVisualizationObject&lt; TConfig &gt;']]],
  ['plotvisualizationobject_3c_20audiovisualizationobjectconfiguration_20_3e',['PlotVisualizationObject&lt; AudioVisualizationObjectConfiguration &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['plotvisualizationobject_3c_20plotvisualizationobjectconfiguration_20_3e',['PlotVisualizationObject&lt; PlotVisualizationObjectConfiguration &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['plotvisualizationobjectconfiguration',['PlotVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_plot_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['plotvisualizationobjectview',['PlotVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft.Psi.Visualization.Views.Visuals2D.PlotVisualizationObjectView'],['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft.Psi.Visualization.Views.Visuals2D.PlotVisualizationObjectView&lt; TConfig &gt;']]],
  ['plotvisualizationobjectview_3c_20audiovisualizationobjectconfiguration_20_3e',['PlotVisualizationObjectView&lt; AudioVisualizationObjectConfiguration &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['plotvisualizationobjectview_3c_20plotvisualizationobjectconfiguration_20_3e',['PlotVisualizationObjectView&lt; PlotVisualizationObjectConfiguration &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['plotvisualizationobjectview_3c_20tconfig_20_3e',['PlotVisualizationObjectView&lt; TConfig &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['pngbitmapencoder',['PngBitmapEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_png_bitmap_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['point',['Point',['../struct_microsoft_1_1_psi_1_1_visualization_1_1_common_1_1_point.html',1,'Microsoft::Psi::Visualization::Common']]],
  ['pointarraytoscatterplotadapter',['PointArrayToScatterPlotAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_point_array_to_scatter_plot_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['points3dvisualizationobject',['Points3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_client_1_1_points3_d_visualization_object.html',1,'Microsoft.Psi.Visualization.Client.Points3DVisualizationObject'],['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_points3_d_visualization_object.html',1,'Microsoft.Psi.Visualization.VisualizationObjects.Points3DVisualizationObject']]],
  ['points3dvisualizationobjectconfiguration',['Points3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_points3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['pointsvisual',['PointsVisual',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals3_d_1_1_points_visual.html',1,'Microsoft::Psi::Visualization::Views::Visuals3D']]],
  ['pool',['Pool',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_pool.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['poolmanager',['PoolManager',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_pool_manager.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['priorityqueue',['PriorityQueue',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_priority_queue.html',1,'Microsoft::Psi::Scheduling']]],
  ['priorityqueue_3c_20workitem_20_3e',['PriorityQueue&lt; WorkItem &gt;',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_priority_queue.html',1,'Microsoft::Psi::Scheduling']]],
  ['processor',['Processor',['../class_microsoft_1_1_psi_1_1_components_1_1_processor.html',1,'Microsoft::Psi::Components']]],
  ['projectto3d',['ProjectTo3D',['../class_microsoft_1_1_psi_1_1_kinect_1_1_project_to3_d.html',1,'Microsoft::Psi::Kinect']]],
  ['propertyinfo',['PropertyInfo',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_info_1_1_property_info.html',1,'Microsoft::Psi::Media::MediaCaptureInfo']]],
  ['propertyvalue',['PropertyValue',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_configuration_1_1_property_value.html',1,'Microsoft::Psi::Media::MediaCaptureConfiguration']]],
  ['psiimagetowriteablebitmapconverter',['PsiImageToWriteableBitmapConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_psi_image_to_writeable_bitmap_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['psistreammetadata',['PsiStreamMetadata',['../class_microsoft_1_1_psi_1_1_psi_stream_metadata.html',1,'Microsoft::Psi']]],
  ['psistudiocontext',['PsiStudioContext',['../class_microsoft_1_1_psi_1_1_psi_studio_1_1_psi_studio_context.html',1,'Microsoft::Psi::PsiStudio']]],
  ['psistudiotemplateselector',['PsiStudioTemplateSelector',['../class_microsoft_1_1_psi_1_1_psi_studio_1_1_psi_studio_template_selector.html',1,'Microsoft::Psi::PsiStudio']]]
];
