var searchData=
[
  ['i3dvisualizationobject_3122',['I3DVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['iadaptinginstantdataprovider_3123',['IAdaptingInstantDataProvider',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_adapting_instant_data_provider.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['ibitmapencoder_3124',['IBitmapEncoder',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_bitmap_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['icameraintrinsics_3125',['ICameraIntrinsics',['../interface_microsoft_1_1_psi_1_1_calibration_1_1_i_camera_intrinsics.html',1,'Microsoft::Psi::Calibration']]],
  ['iconsourcepath_3126',['IconSourcePath',['../class_microsoft_1_1_psi_1_1_visualization_1_1_common_1_1_icon_source_path.html',1,'Microsoft::Psi::Visualization::Common']]],
  ['iconsumer_3127',['IConsumer',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20audiobuffer_20_3e_3128',['IConsumer&lt; AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20t_20_3e_3129',['IConsumer&lt; T &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20tin_5b_5d_3e_3130',['IConsumer&lt; TIn[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumerproducer_3131',['IConsumerProducer',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['iconsumerproducer_3c_20audiobuffer_2c_20bool_20_3e_3132',['IConsumerProducer&lt; AudioBuffer, bool &gt;',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['icontext_3133',['IContext',['../interface_microsoft_1_1_psi_1_1_finite_state_machine_1_1_i_context.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['idepthdevicecalibrationinfo_3134',['IDepthDeviceCalibrationInfo',['../interface_microsoft_1_1_psi_1_1_calibration_1_1_i_depth_device_calibration_info.html',1,'Microsoft::Psi::Calibration']]],
  ['iemitter_3135',['IEmitter',['../interface_microsoft_1_1_psi_1_1_i_emitter.html',1,'Microsoft::Psi']]],
  ['iformatdeserializer_3136',['IFormatDeserializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_format_deserializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['iformatserializer_3137',['IFormatSerializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_format_serializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['iimagecompressor_3138',['IImageCompressor',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_image_compressor.html',1,'Microsoft::Psi::Imaging']]],
  ['iindexer_3139',['IIndexer',['../interface_microsoft_1_1_psi_1_1_arrays_1_1_i_indexer.html',1,'Microsoft::Psi::Arrays']]],
  ['iinstantvisualizationcontainer_3140',['IInstantVisualizationContainer',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_panels_1_1_i_instant_visualization_container.html',1,'Microsoft::Psi::Visualization::VisualizationPanels']]],
  ['iinterval_3141',['IInterval',['../interface_microsoft_1_1_psi_1_1_i_interval.html',1,'Microsoft::Psi']]],
  ['iintervalendpoint_3142',['IIntervalEndpoint',['../interface_microsoft_1_1_psi_1_1_i_interval_endpoint.html',1,'Microsoft::Psi']]],
  ['ikinectfacedetector_3143',['IKinectFaceDetector',['../interface_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_i_kinect_face_detector.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['ikinectsensor_3144',['IKinectSensor',['../interface_microsoft_1_1_psi_1_1_kinect_1_1_i_kinect_sensor.html',1,'Microsoft::Psi::Kinect']]],
  ['image_3145',['Image',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image.html',1,'Microsoft::Psi::Imaging']]],
  ['imageanalyzer_3146',['ImageAnalyzer',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_vision_1_1_image_analyzer.html',1,'Microsoft::Psi::CognitiveServices::Vision']]],
  ['imageanalyzerconfiguration_3147',['ImageAnalyzerConfiguration',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_vision_1_1_image_analyzer_configuration.html',1,'Microsoft::Psi::CognitiveServices::Vision']]],
  ['imagecompressor_3148',['ImageCompressor',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_compressor.html',1,'Microsoft::Psi::Imaging']]],
  ['imagedecoder_3149',['ImageDecoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_decoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imageencoder_3150',['ImageEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imageframe_3151',['ImageFrame',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_internal_1_1_image_frame.html',1,'Microsoft::Psi::Media::MediaCaptureInternal']]],
  ['imagepool_3152',['ImagePool',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_pool.html',1,'Microsoft::Psi::Imaging']]],
  ['imagetransformer_3153',['ImageTransformer',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_transformer.html',1,'Microsoft::Psi::Imaging']]],
  ['imagevisualizationobject_3154',['ImageVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_image_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['imagevisualizationobjectbase_3155',['ImageVisualizationObjectBase',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_image_visualization_object_base.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['imagevisualizationobjectview_3156',['ImageVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_image_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['imagingoperators_3157',['ImagingOperators',['../class_microsoft_1_1_psi_1_1_imaging_1_1_imaging_operators.html',1,'Microsoft::Psi::Imaging']]],
  ['imediacapture_3158',['IMediaCapture',['../interface_microsoft_1_1_psi_1_1_media_1_1_i_media_capture.html',1,'Microsoft::Psi::Media']]],
  ['imodelvisual3dvisualizationobject_3159',['IModelVisual3DVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i_model_visual3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['importer_3160',['Importer',['../class_microsoft_1_1_psi_1_1_data_1_1_importer.html',1,'Microsoft::Psi::Data']]],
  ['indexdefinition_3161',['IndexDefinition',['../class_microsoft_1_1_psi_1_1_arrays_1_1_index_definition.html',1,'Microsoft::Psi::Arrays']]],
  ['indexentry_3162',['IndexEntry',['../struct_microsoft_1_1_psi_1_1_persistence_1_1_index_entry.html',1,'Microsoft::Psi::Persistence']]],
  ['indexer_3163',['Indexer',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer.html',1,'Microsoft::Psi::Arrays']]],
  ['indexer2d_3164',['Indexer2d',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer2d.html',1,'Microsoft::Psi::Arrays']]],
  ['indexernd_3165',['IndexerNd',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer_nd.html',1,'Microsoft::Psi::Arrays']]],
  ['indexhelper_3166',['IndexHelper',['../class_microsoft_1_1_psi_1_1_visualization_1_1_helpers_1_1_index_helper.html',1,'Microsoft::Psi::Visualization::Helpers']]],
  ['instant2dvisualizationobject_3167',['Instant2DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant2_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant2dvisualizationobject_3c_20pipelinediagnostics_20_3e_3168',['Instant2DVisualizationObject&lt; PipelineDiagnostics &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant2_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobject_3169',['Instant3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobject_3c_20coordinatesystem_20_3e_3170',['Instant3DVisualizationObject&lt; CoordinateSystem &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobjectcontractresolver_3171',['Instant3DVisualizationObjectContractResolver',['../class_microsoft_1_1_psi_1_1_visualization_1_1_serialization_1_1_instant3_d_visualization_object_contract_resolver.html',1,'Microsoft::Psi::Visualization::Serialization']]],
  ['instantdatatarget_3172',['InstantDataTarget',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_instant_data_target.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['instantvisualizationcontainer_3173',['InstantVisualizationContainer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_panels_1_1_instant_visualization_container.html',1,'Microsoft::Psi::Visualization::VisualizationPanels']]],
  ['instantvisualizationcontainerview_3174',['InstantVisualizationContainerView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_instant_visualization_container_view.html',1,'Microsoft::Psi::Visualization::Views']]],
  ['instantvisualizationobject_3175',['InstantVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instantvisualizationplaceholderpanel_3176',['InstantVisualizationPlaceholderPanel',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_panels_1_1_instant_visualization_placeholder_panel.html',1,'Microsoft::Psi::Visualization::VisualizationPanels']]],
  ['instantvisualizationplaceholderpanelview_3177',['InstantVisualizationPlaceholderPanelView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_instant_visualization_placeholder_panel_view.html',1,'Microsoft::Psi::Visualization::Views']]],
  ['integertoboolconverter_3178',['IntegerToBoolConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_integer_to_bool_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['integertovalueconverter_3179',['IntegerToValueConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_integer_to_value_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['integertovalueconverter_3c_20bool_20_3e_3180',['IntegerToValueConverter&lt; bool &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_integer_to_value_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['intent_3181',['Intent',['../class_microsoft_1_1_psi_1_1_language_1_1_intent.html',1,'Microsoft::Psi::Language']]],
  ['intentdata_3182',['IntentData',['../class_microsoft_1_1_psi_1_1_language_1_1_intent_data.html',1,'Microsoft::Psi::Language']]],
  ['interpolationresult_3183',['InterpolationResult',['../struct_microsoft_1_1_psi_1_1_interpolation_result.html',1,'Microsoft::Psi']]],
  ['interpolationresult_3c_20tinterpolation_20_3e_3184',['InterpolationResult&lt; TInterpolation &gt;',['../struct_microsoft_1_1_psi_1_1_interpolation_result.html',1,'Microsoft::Psi']]],
  ['interpolator_3185',['Interpolator',['../class_microsoft_1_1_psi_1_1_interpolator.html',1,'Microsoft::Psi']]],
  ['interpolator_3c_20tsecondary_2c_20tinterpolation_20_3e_3186',['Interpolator&lt; TSecondary, TInterpolation &gt;',['../class_microsoft_1_1_psi_1_1_interpolator.html',1,'Microsoft::Psi']]],
  ['interval_3187',['Interval',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20datetime_2c_20timespan_2c_20intervalendpoint_3c_20datetime_20_3e_2c_20timeinterval_20_3e_3188',['Interval&lt; DateTime, TimeSpan, IntervalEndpoint&lt; DateTime &gt;, TimeInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20double_2c_20double_2c_20intervalendpoint_3c_20double_20_3e_2c_20realinterval_20_3e_3189',['Interval&lt; double, double, IntervalEndpoint&lt; double &gt;, RealInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20int_2c_20int_2c_20intervalendpoint_3c_20int_20_3e_2c_20intinterval_20_3e_3190',['Interval&lt; int, int, IntervalEndpoint&lt; int &gt;, IntInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20timespan_2c_20timespan_2c_20intervalendpoint_3c_20timespan_20_3e_2c_20relativetimeinterval_20_3e_3191',['Interval&lt; TimeSpan, TimeSpan, IntervalEndpoint&lt; TimeSpan &gt;, RelativeTimeInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['intervaldata_3192',['IntervalData',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_interval_data.html',1,'Microsoft.Psi.Visualization.Data.IntervalData'],['../struct_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_interval_data.html',1,'Microsoft.Psi.Visualization.Data.IntervalData&lt; T &gt;']]],
  ['intervalendpoint_3193',['IntervalEndpoint',['../class_microsoft_1_1_psi_1_1_interval_endpoint.html',1,'Microsoft::Psi']]],
  ['intinterval_3194',['IntInterval',['../class_microsoft_1_1_psi_1_1_int_interval.html',1,'Microsoft::Psi']]],
  ['inttodoubleadapter_3195',['IntToDoubleAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_int_to_double_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['ipartition_3196',['IPartition',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_partition.html',1,'Microsoft::Psi::Data']]],
  ['iperfcountercollection_3197',['IPerfCounterCollection',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20emittercounters_20_3e_3198',['IPerfCounterCollection&lt; EmitterCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20priorityqueuecounters_20_3e_3199',['IPerfCounterCollection&lt; PriorityQueueCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20receivercounters_20_3e_3200',['IPerfCounterCollection&lt; ReceiverCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20schedulercounters_20_3e_3201',['IPerfCounterCollection&lt; SchedulerCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcounters_3202',['IPerfCounters',['../interface_microsoft_1_1_psi_1_1_i_perf_counters.html',1,'Microsoft::Psi']]],
  ['ipersistentformatdeserializer_3203',['IPersistentFormatDeserializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_persistent_format_deserializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['ipersistentformatserializer_3204',['IPersistentFormatSerializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_persistent_format_serializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['ipool_3205',['IPool',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_pool.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['iproducer_3206',['IProducer',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20audiobuffer_20_3e_3207',['IProducer&lt; AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20microsoft_2epsi_2eaudio_2emicrosoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e_3208',['IProducer&lt; Microsoft.Psi.Audio.Microsoft::Psi::Audio::AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20t_20_3e_3209',['IProducer&lt; T &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20tout_5b_5d_3e_3210',['IProducer&lt; TOut[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['irealsensedeviceunmanaged_3211',['IRealSenseDeviceUnmanaged',['../struct_i_real_sense_device_unmanaged.html',1,'']]],
  ['ireceiver_3212',['IReceiver',['../interface_microsoft_1_1_psi_1_1_i_receiver.html',1,'Microsoft::Psi']]],
  ['irecyclingpool_3213',['IRecyclingPool',['../interface_microsoft_1_1_psi_1_1_i_recycling_pool.html',1,'Microsoft::Psi']]],
  ['irecyclingpool_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20tinput_20_3e_20_3e_3214',['IRecyclingPool&lt; Microsoft::Psi::Message&lt; TInput &gt; &gt;',['../interface_microsoft_1_1_psi_1_1_i_recycling_pool.html',1,'Microsoft::Psi']]],
  ['iserializer_3215',['ISerializer',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20bufferreader_20_3e_3216',['ISerializer&lt; BufferReader &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20byte_5b_5d_3e_3217',['ISerializer&lt; byte[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20image_20_3e_3218',['ISerializer&lt; Image &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20string_20_3e_3219',['ISerializer&lt; string &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20string_5b_5d_3e_3220',['ISerializer&lt; string[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20t_5b_5d_3e_3221',['ISerializer&lt; T[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20unmanagedbuffer_20_3e_3222',['ISerializer&lt; UnmanagedBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['isimplereader_3223',['ISimpleReader',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_simple_reader.html',1,'Microsoft::Psi::Data']]],
  ['isimplewriter_3224',['ISimpleWriter',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_simple_writer.html',1,'Microsoft::Psi::Data']]],
  ['isourcecomponent_3225',['ISourceComponent',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_source_component.html',1,'Microsoft::Psi::Components']]],
  ['ispeechrecognitionalternate_3226',['ISpeechRecognitionAlternate',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_speech_recognition_alternate.html',1,'Microsoft::Psi::Speech']]],
  ['ispeechrecognitionresult_3227',['ISpeechRecognitionResult',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['istreamadapter_3228',['IStreamAdapter',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamingspeechrecognitionresult_3229',['IStreamingSpeechRecognitionResult',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_streaming_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['istreammetadata_3230',['IStreamMetadata',['../interface_microsoft_1_1_psi_1_1_i_stream_metadata.html',1,'Microsoft::Psi']]],
  ['istreamreader_3231',['IStreamReader',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_reader.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamsummary_3232',['IStreamSummary',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_summary.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamvisualizationobject_3233',['IStreamVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i_stream_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['isummarizer_3234',['ISummarizer',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft.Psi.Visualization.Data.ISummarizer'],['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft.Psi.Visualization.Data.ISummarizer&lt; TSrc, TDest &gt;']]],
  ['isummarizer_3c_20tsrc_2c_20tdest_20_3e_3235',['ISummarizer&lt; TSrc, TDest &gt;',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]]
];
