var searchData=
[
  ['pair_3349',['Pair',['../class_microsoft_1_1_psi_1_1_components_1_1_pair.html',1,'Microsoft::Psi::Components']]],
  ['parallelfixedlength_3350',['ParallelFixedLength',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel_fixed_length.html',1,'Microsoft::Psi::Components']]],
  ['parallelsparsedo_3351',['ParallelSparseDo',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel_sparse_do.html',1,'Microsoft::Psi::Components']]],
  ['parallelsparseselect_3352',['ParallelSparseSelect',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel_sparse_select.html',1,'Microsoft::Psi::Components']]],
  ['parallelsparsesplitter_3353',['ParallelSparseSplitter',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel_sparse_splitter.html',1,'Microsoft::Psi::Components']]],
  ['parallelvariablelength_3354',['ParallelVariableLength',['../class_microsoft_1_1_psi_1_1_components_1_1_parallel_variable_length.html',1,'Microsoft::Psi::Components']]],
  ['partialrecognitionresult_3355',['PartialRecognitionResult',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_partial_recognition_result.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['partialspeechresponseeventargs_3356',['PartialSpeechResponseEventArgs',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_partial_speech_response_event_args.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['partition_3357',['Partition',['../class_microsoft_1_1_psi_1_1_data_1_1_partition.html',1,'Microsoft::Psi::Data']]],
  ['partitionviewmodel_3358',['PartitionViewModel',['../class_microsoft_1_1_psi_1_1_visualization_1_1_view_models_1_1_partition_view_model.html',1,'Microsoft::Psi::Visualization::ViewModels']]],
  ['passthroughadapter_3359',['PassthroughAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_passthrough_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['passthroughconverter_3360',['PassThroughConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_pass_through_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['perfcountercollection_3361',['PerfCounterCollection',['../class_microsoft_1_1_psi_1_1_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['perfcounters_3362',['PerfCounters',['../class_microsoft_1_1_psi_1_1_perf_counters.html',1,'Microsoft::Psi']]],
  ['personalitychat_3363',['PersonalityChat',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_language_1_1_personality_chat.html',1,'Microsoft::Psi::CognitiveServices::Language']]],
  ['personalitychatconfiguration_3364',['PersonalityChatConfiguration',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_language_1_1_personality_chat_configuration.html',1,'Microsoft::Psi::CognitiveServices::Language']]],
  ['persongroup_3365',['PersonGroup',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_face_1_1_person_group.html',1,'Microsoft::Psi::CognitiveServices::Face']]],
  ['persongrouptasks_3366',['PersonGroupTasks',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_face_1_1_person_group_tasks.html',1,'Microsoft::Psi::CognitiveServices::Face']]],
  ['phonemereachedeventdata_3367',['PhonemeReachedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_phoneme_reached_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['pieslicearrowsvisual3d_3368',['PieSliceArrowsVisual3D',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals3_d_1_1_pie_slice_arrows_visual3_d.html',1,'Microsoft::Psi::Visualization::Views::Visuals3D']]],
  ['pipeline_3369',['Pipeline',['../class_microsoft_1_1_psi_1_1_pipeline.html',1,'Microsoft::Psi']]],
  ['pipelinecompletedeventargs_3370',['PipelineCompletedEventArgs',['../class_microsoft_1_1_psi_1_1_pipeline_completed_event_args.html',1,'Microsoft::Psi']]],
  ['pipelinediagnostics_3371',['PipelineDiagnostics',['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics.html',1,'Microsoft::Psi::Diagnostics']]],
  ['pipelinediagnosticsvisualizationmodel_3372',['PipelineDiagnosticsVisualizationModel',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_pipeline_diagnostics_visualization_model.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['pipelinediagnosticsvisualizationobject_3373',['PipelineDiagnosticsVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_pipeline_diagnostics_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['pipelinediagnosticsvisualizationobjectview_3374',['PipelineDiagnosticsVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_pipeline_diagnostics_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['pipelinediagnosticsvisualizationpresenter_3375',['PipelineDiagnosticsVisualizationPresenter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_pipeline_diagnostics_visualization_presenter.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['pipelineelementdiagnostics_3376',['PipelineElementDiagnostics',['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_internal_1_1_pipeline_element_diagnostics.html',1,'Microsoft.Psi.Diagnostics.PipelineDiagnosticsInternal.PipelineElementDiagnostics'],['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_1_1_pipeline_element_diagnostics.html',1,'Microsoft.Psi.Diagnostics.PipelineDiagnostics.PipelineElementDiagnostics']]],
  ['pipelineexceptionnothandledeventargs_3377',['PipelineExceptionNotHandledEventArgs',['../class_microsoft_1_1_psi_1_1_pipeline_exception_not_handled_event_args.html',1,'Microsoft::Psi']]],
  ['pipelineruneventargs_3378',['PipelineRunEventArgs',['../class_microsoft_1_1_psi_1_1_pipeline_run_event_args.html',1,'Microsoft::Psi']]],
  ['pixelformat_3379',['PixelFormat',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_internal_1_1_pixel_format.html',1,'Microsoft::Psi::Media::MediaCaptureInternal']]],
  ['pixelformatextensions_3380',['PixelFormatExtensions',['../class_microsoft_1_1_psi_1_1_imaging_1_1_pixel_format_extensions.html',1,'Microsoft::Psi::Imaging']]],
  ['pixelformathelper_3381',['PixelFormatHelper',['../class_microsoft_1_1_psi_1_1_imaging_1_1_pixel_format_helper.html',1,'Microsoft::Psi::Imaging']]],
  ['placementconverter_3382',['PlacementConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_placement_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['plotvisualizationobject_3383',['PlotVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft.Psi.Visualization.VisualizationObjects.PlotVisualizationObject'],['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft.Psi.Visualization.VisualizationObjects.PlotVisualizationObject&lt; TData &gt;']]],
  ['plotvisualizationobject_3c_20double_20_3e_3384',['PlotVisualizationObject&lt; double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['plotvisualizationobject_3c_20object_20_3e_3385',['PlotVisualizationObject&lt; object &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_plot_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['plotvisualizationobjectview_3386',['PlotVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft.Psi.Visualization.Views.Visuals2D.PlotVisualizationObjectView'],['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft.Psi.Visualization.Views.Visuals2D.PlotVisualizationObjectView&lt; TPlotVisualizationObject, TData &gt;']]],
  ['plotvisualizationobjectview_3c_20audiovisualizationobject_2c_20double_20_3e_3387',['PlotVisualizationObjectView&lt; AudioVisualizationObject, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['plotvisualizationobjectview_3c_20messagevisualizationobject_2c_20object_20_3e_3388',['PlotVisualizationObjectView&lt; MessageVisualizationObject, object &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['plotvisualizationobjectview_3c_20plotvisualizationobject_2c_20double_20_3e_3389',['PlotVisualizationObjectView&lt; PlotVisualizationObject, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['plotvisualizationobjectview_3c_20tplotvisualizationobject_2c_20tdata_20_3e_3390',['PlotVisualizationObjectView&lt; TPlotVisualizationObject, TData &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['pngbitmapencoder_3391',['PngBitmapEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_png_bitmap_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['pointarraytoscatterplotadapter_3392',['PointArrayToScatterPlotAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_point_array_to_scatter_plot_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['points3dvisualizationobject_3393',['Points3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_points3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['pointsvisual_3394',['PointsVisual',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals3_d_1_1_points_visual.html',1,'Microsoft::Psi::Visualization::Views::Visuals3D']]],
  ['pool_3395',['Pool',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_pool.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['poolmanager_3396',['PoolManager',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_pool_manager.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['priorityqueue_3397',['PriorityQueue',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_priority_queue.html',1,'Microsoft::Psi::Scheduling']]],
  ['priorityqueue_3c_20workitem_20_3e_3398',['PriorityQueue&lt; WorkItem &gt;',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_priority_queue.html',1,'Microsoft::Psi::Scheduling']]],
  ['processor_3399',['Processor',['../class_microsoft_1_1_psi_1_1_components_1_1_processor.html',1,'Microsoft::Psi::Components']]],
  ['program_3400',['Program',['../class_psi_store_tool_1_1_program.html',1,'PsiStoreTool']]],
  ['projectto3d_3401',['ProjectTo3D',['../class_microsoft_1_1_psi_1_1_calibration_1_1_project_to3_d.html',1,'Microsoft::Psi::Calibration']]],
  ['propertyinfo_3402',['PropertyInfo',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_info_1_1_property_info.html',1,'Microsoft::Psi::Media::MediaCaptureInfo']]],
  ['propertyvalue_3403',['PropertyValue',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_configuration_1_1_property_value.html',1,'Microsoft::Psi::Media::MediaCaptureConfiguration']]],
  ['psiimagetowriteablebitmapconverter_3404',['PsiImageToWriteableBitmapConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_psi_image_to_writeable_bitmap_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['psistreammetadata_3405',['PsiStreamMetadata',['../class_microsoft_1_1_psi_1_1_psi_stream_metadata.html',1,'Microsoft::Psi']]]
];
