var searchData=
[
  ['safeserializationbinder_3446',['SafeSerializationBinder',['../class_microsoft_1_1_psi_1_1_data_1_1_helpers_1_1_safe_serialization_binder.html',1,'Microsoft::Psi::Data::Helpers']]],
  ['scatterplanardirectionvisual_3447',['ScatterPlanarDirectionVisual',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals3_d_1_1_scatter_planar_direction_visual.html',1,'Microsoft::Psi::Visualization::Views::Visuals3D']]],
  ['scatterplanardirectionvisualizationobject_3448',['ScatterPlanarDirectionVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_scatter_planar_direction_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['scatterplotvisualizationobject_3449',['ScatterPlotVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_scatter_plot_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['scatterplotvisualizationobjectview_3450',['ScatterPlotVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_scatter_plot_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['scatterrectanglevisualizationobject_3451',['ScatterRectangleVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_scatter_rectangle_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['scatterrectanglevisualizationobjectview_3452',['ScatterRectangleVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_scatter_rectangle_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['scheduler_3453',['Scheduler',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_scheduler.html',1,'Microsoft::Psi::Scheduling']]],
  ['schedulercontext_3454',['SchedulerContext',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_scheduler_context.html',1,'Microsoft::Psi::Scheduling']]],
  ['sensor_3455',['Sensor',['../class_microsoft_1_1_psi_1_1_device_management_1_1_camera_device_info_1_1_sensor.html',1,'Microsoft::Psi::DeviceManagement::CameraDeviceInfo']]],
  ['serializationcontext_3456',['SerializationContext',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_context.html',1,'Microsoft::Psi::Serialization']]],
  ['serializationhandler_3457',['SerializationHandler',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft.Psi.Serialization.SerializationHandler&lt; T &gt;'],['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft.Psi.Serialization.SerializationHandler']]],
  ['serializationhandler_3c_20sharedcontainer_3c_20t_20_3e_20_3e_3458',['SerializationHandler&lt; SharedContainer&lt; T &gt; &gt;',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft::Psi::Serialization']]],
  ['serializationhandler_3c_20t_20_3e_3459',['SerializationHandler&lt; T &gt;',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft::Psi::Serialization']]],
  ['serializer_3460',['Serializer',['../class_microsoft_1_1_psi_1_1_serializer.html',1,'Microsoft::Psi']]],
  ['serializerattribute_3461',['SerializerAttribute',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serializer_attribute.html',1,'Microsoft::Psi::Serialization']]],
  ['session_3462',['Session',['../class_microsoft_1_1_psi_1_1_data_1_1_session.html',1,'Microsoft::Psi::Data']]],
  ['sessionimporter_3463',['SessionImporter',['../class_microsoft_1_1_psi_1_1_data_1_1_session_importer.html',1,'Microsoft::Psi::Data']]],
  ['sessionviewmodel_3464',['SessionViewModel',['../class_microsoft_1_1_psi_1_1_visualization_1_1_view_models_1_1_session_view_model.html',1,'Microsoft::Psi::Visualization::ViewModels']]],
  ['shared_3465',['Shared',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft.Psi.Shared&lt; T &gt;'],['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft.Psi.Shared']]],
  ['shared_3c_20imaging_2eimage_20_3e_3466',['Shared&lt; Imaging.Image &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['shared_3c_20metadatacache_20_3e_3467',['Shared&lt; MetadataCache &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['shared_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aimage_20_3e_3468',['Shared&lt; Microsoft::Psi::Imaging::Image &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['shared_3c_20pageindexcache_20_3e_3469',['Shared&lt; PageIndexCache &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['sharedarraypool_3470',['SharedArrayPool',['../class_microsoft_1_1_psi_1_1_shared_array_pool.html',1,'Microsoft::Psi']]],
  ['sharedpool_3471',['SharedPool',['../class_microsoft_1_1_psi_1_1_shared_pool.html',1,'Microsoft::Psi']]],
  ['sharedpool_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aencodedimage_20_3e_3472',['SharedPool&lt; Microsoft::Psi::Imaging::EncodedImage &gt;',['../class_microsoft_1_1_psi_1_1_shared_pool.html',1,'Microsoft::Psi']]],
  ['simpleconsumer_3473',['SimpleConsumer',['../class_microsoft_1_1_psi_1_1_components_1_1_simple_consumer.html',1,'Microsoft::Psi::Components']]],
  ['simpleconsumer_3c_20audiobuffer_20_3e_3474',['SimpleConsumer&lt; AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_simple_consumer.html',1,'Microsoft::Psi::Components']]],
  ['simplereader_3475',['SimpleReader',['../class_microsoft_1_1_psi_1_1_data_1_1_simple_reader.html',1,'Microsoft::Psi::Data']]],
  ['simplesemaphore_3476',['SimpleSemaphore',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_simple_semaphore.html',1,'Microsoft::Psi::Scheduling']]],
  ['simplevoiceactivitydetector_3477',['SimpleVoiceActivityDetector',['../class_microsoft_1_1_psi_1_1_speech_1_1_simple_voice_activity_detector.html',1,'Microsoft::Psi::Speech']]],
  ['simplevoiceactivitydetectorconfiguration_3478',['SimpleVoiceActivityDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_simple_voice_activity_detector_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['solvedboard_3479',['SolvedBoard',['../class_microsoft_1_1_psi_1_1_calibration_1_1_multi_camera_calibration_1_1_solved_board.html',1,'Microsoft::Psi::Calibration::MultiCameraCalibration']]],
  ['sourcereadercallback_3480',['SourceReaderCallback',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_source_reader_callback.html',1,'Microsoft::Psi::Media_Interop']]],
  ['speakcompletedeventdata_3481',['SpeakCompletedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_speak_completed_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['speakprogresseventdata_3482',['SpeakProgressEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_speak_progress_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['speakstartedeventdata_3483',['SpeakStartedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_speak_started_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['specific_3484',['Specific',['../class_microsoft_1_1_psi_1_1_platform_1_1_specific.html',1,'Microsoft::Psi::Platform']]],
  ['spectralentropy_3485',['SpectralEntropy',['../class_microsoft_1_1_psi_1_1_audio_1_1_spectral_entropy.html',1,'Microsoft::Psi::Audio']]],
  ['speecherroreventargs_3486',['SpeechErrorEventArgs',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_speech_error_event_args.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['speechrecognitionalternate_3487',['SpeechRecognitionAlternate',['../class_microsoft_1_1_psi_1_1_speech_1_1_speech_recognition_alternate.html',1,'Microsoft::Psi::Speech']]],
  ['speechrecognitionresult_3488',['SpeechRecognitionResult',['../class_microsoft_1_1_psi_1_1_speech_1_1_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['speechrecognitionvisualizationobject_3489',['SpeechRecognitionVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_speech_recognition_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['speechrecognitionvisualizationobjectview_3490',['SpeechRecognitionVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_speech_recognition_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['speechresponseeventargs_3491',['SpeechResponseEventArgs',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_speech_response_event_args.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['speechresult_3492',['SpeechResult',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_speech_result.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['splitter_3493',['Splitter',['../class_microsoft_1_1_psi_1_1_components_1_1_splitter.html',1,'Microsoft::Psi::Components']]],
  ['splitter_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20microsoft_3a_3apsi_3a_3acommon_3a_3abufferreader_20_3e_2c_20int_20_3e_3494',['Splitter&lt; Microsoft::Psi::Message&lt; Microsoft::Psi::Common::BufferReader &gt;, int &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_splitter.html',1,'Microsoft::Psi::Components']]],
  ['sprite3dvisualizationobject_3495',['Sprite3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_sprite3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['spritevisual_3496',['SpriteVisual',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals3_d_1_1_sprite_visual.html',1,'Microsoft::Psi::Visualization::Views::Visuals3D']]],
  ['state_3497',['State',['../class_microsoft_1_1_psi_1_1_finite_state_machine_1_1_state.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['statechangedeventdata_3498',['StateChangedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_state_changed_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['store_3499',['Store',['../class_microsoft_1_1_psi_1_1_store.html',1,'Microsoft::Psi']]],
  ['storepartition_3500',['StorePartition',['../class_microsoft_1_1_psi_1_1_data_1_1_store_partition.html',1,'Microsoft::Psi::Data']]],
  ['storereader_3501',['StoreReader',['../class_microsoft_1_1_psi_1_1_persistence_1_1_store_reader.html',1,'Microsoft::Psi::Persistence']]],
  ['storewriter_3502',['StoreWriter',['../class_microsoft_1_1_psi_1_1_persistence_1_1_store_writer.html',1,'Microsoft::Psi::Persistence']]],
  ['streamadapter_3503',['StreamAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapter_3c_20bool_2c_20double_20_3e_3504',['StreamAdapter&lt; bool, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapter_3c_20float_2c_20double_20_3e_3505',['StreamAdapter&lt; float, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapter_3c_20int_2c_20double_20_3e_3506',['StreamAdapter&lt; int, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapter_3c_20t_2c_20object_20_3e_3507',['StreamAdapter&lt; T, object &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapter_3c_20t_2c_20t_20_3e_3508',['StreamAdapter&lt; T, T &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapter_3c_20timespan_2c_20double_20_3e_3509',['StreamAdapter&lt; TimeSpan, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamadapterattribute_3510',['StreamAdapterAttribute',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_stream_adapter_attribute.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['streamadaptermetadata_3511',['StreamAdapterMetadata',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_stream_adapter_metadata.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['streambinding_3512',['StreamBinding',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_binding.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamenumerable_3513',['StreamEnumerable',['../class_microsoft_1_1_psi_1_1_operators_1_1_stream_enumerable.html',1,'Microsoft::Psi::Operators']]],
  ['streamingspeechrecognitionresult_3514',['StreamingSpeechRecognitionResult',['../class_microsoft_1_1_psi_1_1_speech_1_1_streaming_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['streamobservable_3515',['StreamObservable',['../class_microsoft_1_1_psi_1_1_operators_1_1_stream_observable.html',1,'Microsoft::Psi::Operators']]],
  ['streamreader_3516',['StreamReader',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_reader.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamsummary_3517',['StreamSummary',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_summary.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamsummarymanager_3518',['StreamSummaryManager',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_summary_manager.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamtreenode_3519',['StreamTreeNode',['../class_microsoft_1_1_psi_1_1_visualization_1_1_view_models_1_1_stream_tree_node.html',1,'Microsoft::Psi::Visualization::ViewModels']]],
  ['streamtreenodetocommandsconverter_3520',['StreamTreeNodeToCommandsConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_stream_tree_node_to_commands_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['streamvisualizationobject_3521',['StreamVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_stream_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['stringwithdurationvisualizationobject_3522',['StringWithDurationVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_string_with_duration_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['stringwithdurationvisualizationobjectview_3523',['StringWithDurationVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_string_with_duration_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['subpipeline_3524',['Subpipeline',['../class_microsoft_1_1_psi_1_1_subpipeline.html',1,'Microsoft::Psi']]],
  ['summarizer_3525',['Summarizer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['summarizer_3c_20audiobuffer_2c_20double_20_3e_3526',['Summarizer&lt; AudioBuffer, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['summarizer_3c_20double_2c_20double_20_3e_3527',['Summarizer&lt; double, double &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['summarizer_3c_20object_2c_20object_20_3e_3528',['Summarizer&lt; object, object &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['summarizerattribute_3529',['SummarizerAttribute',['../class_microsoft_1_1_psi_1_1_visualization_1_1_summarizers_1_1_summarizer_attribute.html',1,'Microsoft::Psi::Visualization::Summarizers']]],
  ['summarizermetadata_3530',['SummarizerMetadata',['../class_microsoft_1_1_psi_1_1_visualization_1_1_summarizers_1_1_summarizer_metadata.html',1,'Microsoft::Psi::Visualization::Summarizers']]],
  ['synchronizationlock_3531',['SynchronizationLock',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_synchronization_lock.html',1,'Microsoft::Psi::Scheduling']]],
  ['systemspeech_3532',['SystemSpeech',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechintentdetector_3533',['SystemSpeechIntentDetector',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_intent_detector.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechintentdetectorconfiguration_3534',['SystemSpeechIntentDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_intent_detector_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechrecognizer_3535',['SystemSpeechRecognizer',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_recognizer.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechrecognizerconfiguration_3536',['SystemSpeechRecognizerConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_recognizer_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechsynthesizer_3537',['SystemSpeechSynthesizer',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechsynthesizerconfiguration_3538',['SystemSpeechSynthesizerConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['systemvoiceactivitydetector_3539',['SystemVoiceActivityDetector',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_voice_activity_detector.html',1,'Microsoft::Psi::Speech']]],
  ['systemvoiceactivitydetectorconfiguration_3540',['SystemVoiceActivityDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_voice_activity_detector_configuration.html',1,'Microsoft::Psi::Speech']]]
];
