var searchData=
[
  ['machine',['Machine',['../class_microsoft_1_1_psi_1_1_finite_state_machine_1_1_machine.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['managedcameracontrolpropertyvalue',['ManagedCameraControlPropertyValue',['../struct_microsoft_1_1_psi_1_1_media___interop_1_1_managed_camera_control_property_value.html',1,'Microsoft::Psi::Media_Interop']]],
  ['match',['Match',['../class_microsoft_1_1_psi_1_1_match.html',1,'Microsoft::Psi']]],
  ['matchresult',['MatchResult',['../struct_microsoft_1_1_psi_1_1_match_result.html',1,'Microsoft::Psi']]],
  ['matchresult_3c_20tsecondary_20_3e',['MatchResult&lt; TSecondary &gt;',['../struct_microsoft_1_1_psi_1_1_match_result.html',1,'Microsoft::Psi']]],
  ['mathnetextensions',['MathNetExtensions',['../class_microsoft_1_1_psi_1_1_visualization_1_1_extensions_1_1_math_net_extensions.html',1,'Microsoft::Psi::Visualization::Extensions']]],
  ['mediacapture',['MediaCapture',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture.html',1,'Microsoft::Psi::Media']]],
  ['mediacaptureconfiguration',['MediaCaptureConfiguration',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_configuration.html',1,'Microsoft::Psi::Media']]],
  ['mediacapturedevice',['MediaCaptureDevice',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_media_capture_device.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mediacaptureinfo',['MediaCaptureInfo',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_info.html',1,'Microsoft::Psi::Media']]],
  ['mediafoundationutility',['MediaFoundationUtility',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_media_foundation_utility.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mediasource',['MediaSource',['../class_microsoft_1_1_psi_1_1_media_1_1_media_source.html',1,'Microsoft::Psi::Media']]],
  ['merger',['Merger',['../class_microsoft_1_1_psi_1_1_components_1_1_merger.html',1,'Microsoft::Psi::Components']]],
  ['merger_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20jtoken_20_3e_2c_20string_20_3e',['Merger&lt; Microsoft::Psi::Message&lt; JToken &gt;, string &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_merger.html',1,'Microsoft::Psi::Components']]],
  ['merger_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20microsoft_3a_3apsi_3a_3acommon_3a_3abufferreader_20_3e_2c_20string_20_3e',['Merger&lt; Microsoft::Psi::Message&lt; Microsoft::Psi::Common::BufferReader &gt;, string &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_merger.html',1,'Microsoft::Psi::Components']]],
  ['message',['Message',['../struct_microsoft_1_1_psi_1_1_message.html',1,'Microsoft.Psi.Message&lt; T &gt;'],['../class_microsoft_1_1_psi_1_1_message.html',1,'Microsoft.Psi.Message']]],
  ['message_3c_20tdata_20_3e',['Message&lt; TData &gt;',['../class_microsoft_1_1_psi_1_1_message.html',1,'Microsoft::Psi']]],
  ['metadata',['Metadata',['../class_microsoft_1_1_psi_1_1_metadata.html',1,'Microsoft::Psi']]],
  ['microsoftspeechrecognizer',['MicrosoftSpeechRecognizer',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech_recognizer.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['microsoftspeechrecognizerconfiguration',['MicrosoftSpeechRecognizerConfiguration',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech_recognizer_configuration.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['mp4writer',['MP4Writer',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_m_p4_writer.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mp4writerconfiguration',['MP4WriterConfiguration',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_m_p4_writer_configuration.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mp4writerunmanageddata',['MP4WriterUnmanagedData',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_m_p4_writer_unmanaged_data.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mpeg4writer',['Mpeg4Writer',['../class_microsoft_1_1_psi_1_1_media_1_1_mpeg4_writer.html',1,'Microsoft::Psi::Media']]],
  ['mpeg4writerconfiguration',['Mpeg4WriterConfiguration',['../class_microsoft_1_1_psi_1_1_media_1_1_mpeg4_writer_configuration.html',1,'Microsoft::Psi::Media']]]
];
