var searchData=
[
  ['cameracalibration',['CameraCalibration',['../class_microsoft_1_1_psi_1_1_calibration_1_1_system_calibration_1_1_camera_calibration.html',1,'Microsoft::Psi::Calibration::SystemCalibration']]],
  ['cameraintrinsics',['CameraIntrinsics',['../class_microsoft_1_1_psi_1_1_calibration_1_1_camera_intrinsics.html',1,'Microsoft::Psi::Calibration']]],
  ['captureformat',['CaptureFormat',['../struct_microsoft_1_1_psi_1_1_media___interop_1_1_capture_format.html',1,'Microsoft::Psi::Media_Interop']]],
  ['circularbufferstream',['CircularBufferStream',['../class_microsoft_1_1_psi_1_1_audio_1_1_circular_buffer_stream.html',1,'Microsoft::Psi::Audio']]],
  ['colorextensions',['ColorExtensions',['../class_microsoft_1_1_psi_1_1_visualization_1_1_extensions_1_1_color_extensions.html',1,'Microsoft::Psi::Visualization::Extensions']]],
  ['comhelper',['ComHelper',['../class_microsoft_1_1_psi_1_1_visualization_1_1_server_1_1_com_helper.html',1,'Microsoft::Psi::Visualization::Server']]],
  ['comnative',['ComNative',['../class_microsoft_1_1_psi_1_1_visualization_1_1_server_1_1_com_native.html',1,'Microsoft::Psi::Visualization::Server']]],
  ['comobservableobject',['ComObservableObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_base_1_1_com_observable_object.html',1,'Microsoft::Psi::Visualization::Base']]],
  ['comserver',['ComServer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_server_1_1_com_server.html',1,'Microsoft::Psi::Visualization::Server']]],
  ['configurationhelper',['ConfigurationHelper',['../class_microsoft_1_1_psi_1_1_configuration_helper.html',1,'Microsoft::Psi']]],
  ['connector',['Connector',['../class_microsoft_1_1_psi_1_1_components_1_1_connector.html',1,'Microsoft::Psi::Components']]],
  ['connector_3c_20microsoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e',['Connector&lt; Microsoft::Psi::Audio::AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_connector.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer',['ConsumerProducer',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20audiobuffer_2c_20audiobuffer_20_3e',['ConsumerProducer&lt; AudioBuffer, AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20audiobuffer_2c_20bool_20_3e',['ConsumerProducer&lt; AudioBuffer, bool &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20audiobuffer_2c_20istreamingspeechrecognitionresult_20_3e',['ConsumerProducer&lt; AudioBuffer, IStreamingSpeechRecognitionResult &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20byte_5b_5d_2c_20byte_5b_5d_3e',['ConsumerProducer&lt; byte[], byte[]&gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20byte_5b_5d_2c_20float_5b_5d_3e',['ConsumerProducer&lt; byte[], float[]&gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20float_5b_5d_2c_20float_20_3e',['ConsumerProducer&lt; float[], float &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20float_5b_5d_2c_20float_5b_5d_3e',['ConsumerProducer&lt; float[], float[]&gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20message_3c_20bufferreader_20_3e_2c_20t_20_3e',['ConsumerProducer&lt; Message&lt; BufferReader &gt;, T &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20string_2c_20audiobuffer_20_3e',['ConsumerProducer&lt; string, AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20t_2c_20t_20_3e',['ConsumerProducer&lt; T, T &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['consumerproducer_3c_20tinput_2c_20toutput_20_3e',['ConsumerProducer&lt; TInput, TOutput &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['customserializer',['CustomSerializer',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_1_1_custom_serializer.html',1,'Microsoft::Psi::Imaging::Image']]]
];
