var searchData=
[
  ['range_3534',['Range',['../struct_microsoft_1_1_psi_1_1_arrays_1_1_range.html',1,'Microsoft::Psi::Arrays']]],
  ['rangesummarizer_3535',['RangeSummarizer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_summarizers_1_1_range_summarizer.html',1,'Microsoft::Psi::Visualization::Summarizers']]],
  ['readrequest_3536',['ReadRequest',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_read_request.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['realinterval_3537',['RealInterval',['../class_microsoft_1_1_psi_1_1_real_interval.html',1,'Microsoft::Psi']]],
  ['realsensedevice_3538',['RealSenseDevice',['../class_microsoft_1_1_psi_1_1_real_sense_1_1_windows_1_1_real_sense_device.html',1,'Microsoft::Psi::RealSense::Windows']]],
  ['realsensedeviceunmanaged_3539',['RealSenseDeviceUnmanaged',['../class_real_sense_device_unmanaged.html',1,'']]],
  ['realsensesensor_3540',['RealSenseSensor',['../class_microsoft_1_1_psi_1_1_real_sense_1_1_windows_1_1_real_sense_sensor.html',1,'Microsoft::Psi::RealSense::Windows']]],
  ['receiver_3541',['Receiver',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20bool_20_3e_3542',['Receiver&lt; bool &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20int_20_3e_3543',['Receiver&lt; int &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e_3544',['Receiver&lt; Microsoft::Psi::Audio::AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20microsoft_3a_3apsi_3a_3ashared_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aimage_20_3e_20_3e_3545',['Receiver&lt; Microsoft::Psi::Shared&lt; Microsoft::Psi::Imaging::Image &gt; &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tin_20_3e_3546',['Receiver&lt; TIn &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tin_5b_5d_3e_3547',['Receiver&lt; TIn[]&gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receiver_3c_20tsecondary_20_3e_3548',['Receiver&lt; TSecondary &gt;',['../class_microsoft_1_1_psi_1_1_receiver.html',1,'Microsoft::Psi']]],
  ['receivercollector_3549',['ReceiverCollector',['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_diagnostics_collector_1_1_receiver_collector.html',1,'Microsoft::Psi::Diagnostics::DiagnosticsCollector']]],
  ['receiverdiagnostics_3550',['ReceiverDiagnostics',['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_internal_1_1_receiver_diagnostics.html',1,'Microsoft.Psi.Diagnostics.PipelineDiagnosticsInternal.ReceiverDiagnostics'],['../class_microsoft_1_1_psi_1_1_diagnostics_1_1_pipeline_diagnostics_1_1_receiver_diagnostics.html',1,'Microsoft.Psi.Diagnostics.PipelineDiagnostics.ReceiverDiagnostics']]],
  ['recognitionresult_3551',['RecognitionResult',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_recognition_result.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['recognizedphrase_3552',['RecognizedPhrase',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_recognized_phrase.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['rect3dlistvisualizationobject_3553',['Rect3DListVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_rect3_d_list_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['rect3dvisualizationobject_3554',['Rect3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_rect3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['recyclingpool_3555',['RecyclingPool',['../class_microsoft_1_1_psi_1_1_recycling_pool.html',1,'Microsoft::Psi']]],
  ['reframe_3556',['Reframe',['../class_microsoft_1_1_psi_1_1_audio_1_1_reframe.html',1,'Microsoft::Psi::Audio']]],
  ['relativeindexwindow_3557',['RelativeIndexWindow',['../class_microsoft_1_1_psi_1_1_components_1_1_relative_index_window.html',1,'Microsoft::Psi::Components']]],
  ['relativepathconverter_3558',['RelativePathConverter',['../class_microsoft_1_1_psi_1_1_data_1_1_converters_1_1_relative_path_converter.html',1,'Microsoft::Psi::Data::Converters']]],
  ['relativetimeinterval_3559',['RelativeTimeInterval',['../class_microsoft_1_1_psi_1_1_relative_time_interval.html',1,'Microsoft::Psi']]],
  ['relativetimewindow_3560',['RelativeTimeWindow',['../class_microsoft_1_1_psi_1_1_components_1_1_relative_time_window.html',1,'Microsoft::Psi::Components']]],
  ['remoteexporter_3561',['RemoteExporter',['../class_microsoft_1_1_psi_1_1_remoting_1_1_remote_exporter.html',1,'Microsoft::Psi::Remoting']]],
  ['remoteimporter_3562',['RemoteImporter',['../class_microsoft_1_1_psi_1_1_remoting_1_1_remote_importer.html',1,'Microsoft::Psi::Remoting']]],
  ['replaydescriptor_3563',['ReplayDescriptor',['../class_microsoft_1_1_psi_1_1_replay_descriptor.html',1,'Microsoft::Psi']]],
  ['reproducible_3564',['Reproducible',['../class_microsoft_1_1_psi_1_1_reproducible.html',1,'Microsoft::Psi']]],
  ['reproducibleinterpolator_3565',['ReproducibleInterpolator',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft.Psi.ReproducibleInterpolator&lt; TIn, TResult &gt;'],['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft.Psi.ReproducibleInterpolator&lt; T &gt;']]],
  ['reproducibleinterpolator_3c_20t_20_3e_3566',['ReproducibleInterpolator&lt; T &gt;',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft::Psi']]],
  ['reproducibleinterpolator_3c_20t_2c_20t_20_3e_3567',['ReproducibleInterpolator&lt; T, T &gt;',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft::Psi']]],
  ['reproducibleinterpolator_3c_20tin_2c_20tout_20_3e_3568',['ReproducibleInterpolator&lt; TIn, TOut &gt;',['../class_microsoft_1_1_psi_1_1_reproducible_interpolator.html',1,'Microsoft::Psi']]],
  ['resources_3569',['Resources',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_resources.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rgbcameracollection_3570',['RGBCameraCollection',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_r_g_b_camera_collection.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rgbcameraenumerator_3571',['RGBCameraEnumerator',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_r_g_b_camera_enumerator.html',1,'Microsoft::Psi::Media_Interop']]],
  ['rotationextensions_3572',['RotationExtensions',['../class_microsoft_1_1_psi_1_1_calibration_1_1_rotation_extensions.html',1,'Microsoft::Psi::Calibration']]],
  ['runtimeinfo_3573',['RuntimeInfo',['../class_microsoft_1_1_psi_1_1_common_1_1_runtime_info.html',1,'Microsoft::Psi::Common']]]
];
