var searchData=
[
  ['i3dvisualizationobject_3240',['I3DVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['iadaptinginstantdataprovider_3241',['IAdaptingInstantDataProvider',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_adapting_instant_data_provider.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['icameraintrinsics_3242',['ICameraIntrinsics',['../interface_microsoft_1_1_psi_1_1_calibration_1_1_i_camera_intrinsics.html',1,'Microsoft::Psi::Calibration']]],
  ['iconsourcepath_3243',['IconSourcePath',['../class_microsoft_1_1_psi_1_1_visualization_1_1_common_1_1_icon_source_path.html',1,'Microsoft::Psi::Visualization::Common']]],
  ['iconsumer_3244',['IConsumer',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20audiobuffer_20_3e_3245',['IConsumer&lt; AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20t_20_3e_3246',['IConsumer&lt; T &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20tin_5b_5d_3e_3247',['IConsumer&lt; TIn[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumerproducer_3248',['IConsumerProducer',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['iconsumerproducer_3c_20audiobuffer_2c_20bool_20_3e_3249',['IConsumerProducer&lt; AudioBuffer, bool &gt;',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['icontext_3250',['IContext',['../interface_microsoft_1_1_psi_1_1_finite_state_machine_1_1_i_context.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['idepthdevicecalibrationinfo_3251',['IDepthDeviceCalibrationInfo',['../interface_microsoft_1_1_psi_1_1_calibration_1_1_i_depth_device_calibration_info.html',1,'Microsoft::Psi::Calibration']]],
  ['idepthimagecompressor_3252',['IDepthImageCompressor',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_depth_image_compressor.html',1,'Microsoft::Psi::Imaging']]],
  ['idepthimagefromstreamdecoder_3253',['IDepthImageFromStreamDecoder',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_depth_image_from_stream_decoder.html',1,'Microsoft::Psi::Imaging']]],
  ['idepthimagetostreamencoder_3254',['IDepthImageToStreamEncoder',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_depth_image_to_stream_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['iemitter_3255',['IEmitter',['../interface_microsoft_1_1_psi_1_1_i_emitter.html',1,'Microsoft::Psi']]],
  ['iformatdeserializer_3256',['IFormatDeserializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_format_deserializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['iformatserializer_3257',['IFormatSerializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_format_serializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['iimagecompressor_3258',['IImageCompressor',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_image_compressor.html',1,'Microsoft::Psi::Imaging']]],
  ['iimagefromstreamdecoder_3259',['IImageFromStreamDecoder',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_image_from_stream_decoder.html',1,'Microsoft::Psi::Imaging']]],
  ['iimagetostreamencoder_3260',['IImageToStreamEncoder',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_image_to_stream_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['iindexer_3261',['IIndexer',['../interface_microsoft_1_1_psi_1_1_arrays_1_1_i_indexer.html',1,'Microsoft::Psi::Arrays']]],
  ['iinstantvisualizationcontainer_3262',['IInstantVisualizationContainer',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_panels_1_1_i_instant_visualization_container.html',1,'Microsoft::Psi::Visualization::VisualizationPanels']]],
  ['iinterval_3263',['IInterval',['../interface_microsoft_1_1_psi_1_1_i_interval.html',1,'Microsoft::Psi']]],
  ['iintervalendpoint_3264',['IIntervalEndpoint',['../interface_microsoft_1_1_psi_1_1_i_interval_endpoint.html',1,'Microsoft::Psi']]],
  ['ikinectfacedetector_3265',['IKinectFaceDetector',['../interface_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_i_kinect_face_detector.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['image_3266',['Image',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image.html',1,'Microsoft::Psi::Imaging']]],
  ['imageanalyzer_3267',['ImageAnalyzer',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_vision_1_1_image_analyzer.html',1,'Microsoft::Psi::CognitiveServices::Vision']]],
  ['imageanalyzerconfiguration_3268',['ImageAnalyzerConfiguration',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_vision_1_1_image_analyzer_configuration.html',1,'Microsoft::Psi::CognitiveServices::Vision']]],
  ['imagebase_3269',['ImageBase',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_base.html',1,'Microsoft::Psi::Imaging']]],
  ['imagecompressor_3270',['ImageCompressor',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_compressor.html',1,'Microsoft::Psi::Imaging']]],
  ['imagedecoder_3271',['ImageDecoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_decoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imageencoder_3272',['ImageEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imageframe_3273',['ImageFrame',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_internal_1_1_image_frame.html',1,'Microsoft::Psi::Media::MediaCaptureInternal']]],
  ['imagefromstreamdecoder_3274',['ImageFromStreamDecoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_from_stream_decoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imagepool_3275',['ImagePool',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_pool.html',1,'Microsoft::Psi::Imaging']]],
  ['imagetojpegstreamencoder_3276',['ImageToJpegStreamEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_to_jpeg_stream_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imagetopngstreamencoder_3277',['ImageToPngStreamEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_to_png_stream_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imagetransformer_3278',['ImageTransformer',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_transformer.html',1,'Microsoft::Psi::Imaging']]],
  ['imagevisualizationobject_3279',['ImageVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_image_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['imagevisualizationobjectbase_3280',['ImageVisualizationObjectBase',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_image_visualization_object_base.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['imagevisualizationobjectview_3281',['ImageVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_image_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['imagingoperators_3282',['ImagingOperators',['../class_microsoft_1_1_psi_1_1_imaging_1_1_imaging_operators.html',1,'Microsoft::Psi::Imaging']]],
  ['imediacapture_3283',['IMediaCapture',['../interface_microsoft_1_1_psi_1_1_media_1_1_i_media_capture.html',1,'Microsoft::Psi::Media']]],
  ['imodelvisual3dvisualizationobject_3284',['IModelVisual3DVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i_model_visual3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['importer_3285',['Importer',['../class_microsoft_1_1_psi_1_1_data_1_1_importer.html',1,'Microsoft::Psi::Data']]],
  ['indexdefinition_3286',['IndexDefinition',['../class_microsoft_1_1_psi_1_1_arrays_1_1_index_definition.html',1,'Microsoft::Psi::Arrays']]],
  ['indexentry_3287',['IndexEntry',['../struct_microsoft_1_1_psi_1_1_persistence_1_1_index_entry.html',1,'Microsoft::Psi::Persistence']]],
  ['indexer_3288',['Indexer',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer.html',1,'Microsoft::Psi::Arrays']]],
  ['indexer2d_3289',['Indexer2d',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer2d.html',1,'Microsoft::Psi::Arrays']]],
  ['indexernd_3290',['IndexerNd',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer_nd.html',1,'Microsoft::Psi::Arrays']]],
  ['indexhelper_3291',['IndexHelper',['../class_microsoft_1_1_psi_1_1_visualization_1_1_helpers_1_1_index_helper.html',1,'Microsoft::Psi::Visualization::Helpers']]],
  ['instant2dvisualizationobject_3292',['Instant2DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant2_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant2dvisualizationobject_3c_20pipelinediagnostics_20_3e_3293',['Instant2DVisualizationObject&lt; PipelineDiagnostics &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant2_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobject_3294',['Instant3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobject_3c_20coordinatesystem_20_3e_3295',['Instant3DVisualizationObject&lt; CoordinateSystem &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobjectcontractresolver_3296',['Instant3DVisualizationObjectContractResolver',['../class_microsoft_1_1_psi_1_1_visualization_1_1_serialization_1_1_instant3_d_visualization_object_contract_resolver.html',1,'Microsoft::Psi::Visualization::Serialization']]],
  ['instantdatatarget_3297',['InstantDataTarget',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_instant_data_target.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['instantvisualizationcontainer_3298',['InstantVisualizationContainer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_panels_1_1_instant_visualization_container.html',1,'Microsoft::Psi::Visualization::VisualizationPanels']]],
  ['instantvisualizationcontainerview_3299',['InstantVisualizationContainerView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_instant_visualization_container_view.html',1,'Microsoft::Psi::Visualization::Views']]],
  ['instantvisualizationobject_3300',['InstantVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instantvisualizationplaceholderpanel_3301',['InstantVisualizationPlaceholderPanel',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_panels_1_1_instant_visualization_placeholder_panel.html',1,'Microsoft::Psi::Visualization::VisualizationPanels']]],
  ['instantvisualizationplaceholderpanelview_3302',['InstantVisualizationPlaceholderPanelView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_instant_visualization_placeholder_panel_view.html',1,'Microsoft::Psi::Visualization::Views']]],
  ['integertoboolconverter_3303',['IntegerToBoolConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_integer_to_bool_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['integertovalueconverter_3304',['IntegerToValueConverter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_integer_to_value_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['integertovalueconverter_3c_20bool_20_3e_3305',['IntegerToValueConverter&lt; bool &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_converters_1_1_integer_to_value_converter.html',1,'Microsoft::Psi::Visualization::Converters']]],
  ['intent_3306',['Intent',['../class_microsoft_1_1_psi_1_1_language_1_1_intent.html',1,'Microsoft::Psi::Language']]],
  ['intentdata_3307',['IntentData',['../class_microsoft_1_1_psi_1_1_language_1_1_intent_data.html',1,'Microsoft::Psi::Language']]],
  ['interpolationresult_3308',['InterpolationResult',['../struct_microsoft_1_1_psi_1_1_interpolation_result.html',1,'Microsoft::Psi']]],
  ['interpolationresult_3c_20tinterpolation_20_3e_3309',['InterpolationResult&lt; TInterpolation &gt;',['../struct_microsoft_1_1_psi_1_1_interpolation_result.html',1,'Microsoft::Psi']]],
  ['interpolator_3310',['Interpolator',['../class_microsoft_1_1_psi_1_1_interpolator.html',1,'Microsoft::Psi']]],
  ['interpolator_3c_20tsecondary_2c_20tinterpolation_20_3e_3311',['Interpolator&lt; TSecondary, TInterpolation &gt;',['../class_microsoft_1_1_psi_1_1_interpolator.html',1,'Microsoft::Psi']]],
  ['interval_3312',['Interval',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20datetime_2c_20timespan_2c_20intervalendpoint_3c_20datetime_20_3e_2c_20timeinterval_20_3e_3313',['Interval&lt; DateTime, TimeSpan, IntervalEndpoint&lt; DateTime &gt;, TimeInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20double_2c_20double_2c_20intervalendpoint_3c_20double_20_3e_2c_20realinterval_20_3e_3314',['Interval&lt; double, double, IntervalEndpoint&lt; double &gt;, RealInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20int_2c_20int_2c_20intervalendpoint_3c_20int_20_3e_2c_20intinterval_20_3e_3315',['Interval&lt; int, int, IntervalEndpoint&lt; int &gt;, IntInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20timespan_2c_20timespan_2c_20intervalendpoint_3c_20timespan_20_3e_2c_20relativetimeinterval_20_3e_3316',['Interval&lt; TimeSpan, TimeSpan, IntervalEndpoint&lt; TimeSpan &gt;, RelativeTimeInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['intervaldata_3317',['IntervalData',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_interval_data.html',1,'Microsoft.Psi.Visualization.Data.IntervalData'],['../struct_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_interval_data.html',1,'Microsoft.Psi.Visualization.Data.IntervalData&lt; T &gt;']]],
  ['intervalendpoint_3318',['IntervalEndpoint',['../class_microsoft_1_1_psi_1_1_interval_endpoint.html',1,'Microsoft::Psi']]],
  ['intinterval_3319',['IntInterval',['../class_microsoft_1_1_psi_1_1_int_interval.html',1,'Microsoft::Psi']]],
  ['inttodoubleadapter_3320',['IntToDoubleAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_int_to_double_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['ipartition_3321',['IPartition',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_partition.html',1,'Microsoft::Psi::Data']]],
  ['iperfcountercollection_3322',['IPerfCounterCollection',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20emittercounters_20_3e_3323',['IPerfCounterCollection&lt; EmitterCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20priorityqueuecounters_20_3e_3324',['IPerfCounterCollection&lt; PriorityQueueCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20receivercounters_20_3e_3325',['IPerfCounterCollection&lt; ReceiverCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20schedulercounters_20_3e_3326',['IPerfCounterCollection&lt; SchedulerCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcounters_3327',['IPerfCounters',['../interface_microsoft_1_1_psi_1_1_i_perf_counters.html',1,'Microsoft::Psi']]],
  ['ipersistentformatdeserializer_3328',['IPersistentFormatDeserializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_persistent_format_deserializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['ipersistentformatserializer_3329',['IPersistentFormatSerializer',['../interface_microsoft_1_1_psi_1_1_interop_1_1_serialization_1_1_i_persistent_format_serializer.html',1,'Microsoft::Psi::Interop::Serialization']]],
  ['ipool_3330',['IPool',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_pool.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['iproducer_3331',['IProducer',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20audio_2emicrosoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e_3332',['IProducer&lt; Audio.Microsoft::Psi::Audio::AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20audiobuffer_20_3e_3333',['IProducer&lt; AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20t_20_3e_3334',['IProducer&lt; T &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20t_5b_5d_3e_3335',['IProducer&lt; T[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20tout_5b_5d_3e_3336',['IProducer&lt; TOut[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['irealsensedeviceunmanaged_3337',['IRealSenseDeviceUnmanaged',['../struct_i_real_sense_device_unmanaged.html',1,'']]],
  ['ireceiver_3338',['IReceiver',['../interface_microsoft_1_1_psi_1_1_i_receiver.html',1,'Microsoft::Psi']]],
  ['irecyclingpool_3339',['IRecyclingPool',['../interface_microsoft_1_1_psi_1_1_i_recycling_pool.html',1,'Microsoft::Psi']]],
  ['irecyclingpool_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20tinput_20_3e_20_3e_3340',['IRecyclingPool&lt; Microsoft::Psi::Message&lt; TInput &gt; &gt;',['../interface_microsoft_1_1_psi_1_1_i_recycling_pool.html',1,'Microsoft::Psi']]],
  ['iserializer_3341',['ISerializer',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20bufferreader_20_3e_3342',['ISerializer&lt; BufferReader &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20byte_5b_5d_3e_3343',['ISerializer&lt; byte[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20string_20_3e_3344',['ISerializer&lt; string &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20string_5b_5d_3e_3345',['ISerializer&lt; string[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20t_5b_5d_3e_3346',['ISerializer&lt; T[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20timage_20_3e_3347',['ISerializer&lt; TImage &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20unmanagedbuffer_20_3e_3348',['ISerializer&lt; UnmanagedBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['isimplereader_3349',['ISimpleReader',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_simple_reader.html',1,'Microsoft::Psi::Data']]],
  ['isimplewriter_3350',['ISimpleWriter',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_simple_writer.html',1,'Microsoft::Psi::Data']]],
  ['isourcecomponent_3351',['ISourceComponent',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_source_component.html',1,'Microsoft::Psi::Components']]],
  ['ispeechrecognitionalternate_3352',['ISpeechRecognitionAlternate',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_speech_recognition_alternate.html',1,'Microsoft::Psi::Speech']]],
  ['ispeechrecognitionresult_3353',['ISpeechRecognitionResult',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['istreamadapter_3354',['IStreamAdapter',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamingspeechrecognitionresult_3355',['IStreamingSpeechRecognitionResult',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_streaming_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['istreammetadata_3356',['IStreamMetadata',['../interface_microsoft_1_1_psi_1_1_i_stream_metadata.html',1,'Microsoft::Psi']]],
  ['istreamreader_3357',['IStreamReader',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_reader.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamsummary_3358',['IStreamSummary',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_summary.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamvisualizationobject_3359',['IStreamVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i_stream_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['isummarizer_3360',['ISummarizer',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft.Psi.Visualization.Data.ISummarizer'],['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft.Psi.Visualization.Data.ISummarizer&lt; TSrc, TDest &gt;']]],
  ['isummarizer_3c_20tsrc_2c_20tdest_20_3e_3361',['ISummarizer&lt; TSrc, TDest &gt;',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]]
];
