var searchData=
[
  ['machine_3276',['Machine',['../class_microsoft_1_1_psi_1_1_finite_state_machine_1_1_machine.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['managedcameracontrolpropertyvalue_3277',['ManagedCameraControlPropertyValue',['../struct_microsoft_1_1_psi_1_1_media___interop_1_1_managed_camera_control_property_value.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mathextensions_3278',['MathExtensions',['../class_microsoft_1_1_psi_1_1_math_extensions.html',1,'Microsoft::Psi']]],
  ['mathnetextensions_3279',['MathNetExtensions',['../class_microsoft_1_1_psi_1_1_visualization_1_1_extensions_1_1_math_net_extensions.html',1,'Microsoft::Psi::Visualization::Extensions']]],
  ['mathnetnullablepoint2dtoscatterplotadapter_3280',['MathNetNullablePoint2DToScatterPlotAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_math_net_nullable_point2_d_to_scatter_plot_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['mathnetnullablepoint3dtowindowspoint3dlistadapter_3281',['MathNetNullablePoint3DToWindowsPoint3DListAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_math_net_nullable_point3_d_to_windows_point3_d_list_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['mathnetpoint3dlisttowindowspoint3dlistadapter_3282',['MathNetPoint3DListToWindowsPoint3DListAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_adapters_1_1_math_net_point3_d_list_to_windows_point3_d_list_adapter.html',1,'Microsoft::Psi::Visualization::Adapters']]],
  ['mediacapture_3283',['MediaCapture',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture.html',1,'Microsoft::Psi::Media']]],
  ['mediacaptureconfiguration_3284',['MediaCaptureConfiguration',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_configuration.html',1,'Microsoft::Psi::Media']]],
  ['mediacapturedevice_3285',['MediaCaptureDevice',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_media_capture_device.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mediacaptureinfo_3286',['MediaCaptureInfo',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_info.html',1,'Microsoft::Psi::Media']]],
  ['mediafoundationutility_3287',['MediaFoundationUtility',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_media_foundation_utility.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mediasource_3288',['MediaSource',['../class_microsoft_1_1_psi_1_1_media_1_1_media_source.html',1,'Microsoft::Psi::Media']]],
  ['merge_3289',['Merge',['../class_microsoft_1_1_psi_1_1_components_1_1_merge.html',1,'Microsoft::Psi::Components']]],
  ['merger_3290',['Merger',['../class_microsoft_1_1_psi_1_1_components_1_1_merger.html',1,'Microsoft::Psi::Components']]],
  ['merger_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20jtoken_20_3e_2c_20string_20_3e_3291',['Merger&lt; Microsoft::Psi::Message&lt; JToken &gt;, string &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_merger.html',1,'Microsoft::Psi::Components']]],
  ['merger_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20microsoft_3a_3apsi_3a_3acommon_3a_3abufferreader_20_3e_2c_20string_20_3e_3292',['Merger&lt; Microsoft::Psi::Message&lt; Microsoft::Psi::Common::BufferReader &gt;, string &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_merger.html',1,'Microsoft::Psi::Components']]],
  ['message_3293',['Message',['../class_microsoft_1_1_psi_1_1_message.html',1,'Microsoft.Psi.Message'],['../struct_microsoft_1_1_psi_1_1_message.html',1,'Microsoft.Psi.Message&lt; T &gt;']]],
  ['message_3c_20tdata_20_3e_3294',['Message&lt; TData &gt;',['../class_microsoft_1_1_psi_1_1_message.html',1,'Microsoft::Psi']]],
  ['messageboxwindow_3295',['MessageBoxWindow',['../class_microsoft_1_1_psi_1_1_visualization_1_1_windows_1_1_message_box_window.html',1,'Microsoft::Psi::Visualization::Windows']]],
  ['messagepackformat_3296',['MessagePackFormat',['../class_microsoft_1_1_psi_1_1_interop_1_1_format_1_1_message_pack_format.html',1,'Microsoft::Psi::Interop::Format']]],
  ['messagevisualizationobject_3297',['MessageVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_message_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['messagevisualizationobjectview_3298',['MessageVisualizationObjectView',['../class_microsoft_1_1_psi_1_1_visualization_1_1_views_1_1_visuals2_d_1_1_message_visualization_object_view.html',1,'Microsoft::Psi::Visualization::Views::Visuals2D']]],
  ['metadata_3299',['Metadata',['../class_microsoft_1_1_psi_1_1_metadata.html',1,'Microsoft::Psi']]],
  ['microsoftspeech_3300',['MicrosoftSpeech',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['microsoftspeechintentdetector_3301',['MicrosoftSpeechIntentDetector',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech_intent_detector.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['microsoftspeechintentdetectorconfiguration_3302',['MicrosoftSpeechIntentDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech_intent_detector_configuration.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['microsoftspeechrecognizer_3303',['MicrosoftSpeechRecognizer',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech_recognizer.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['microsoftspeechrecognizerconfiguration_3304',['MicrosoftSpeechRecognizerConfiguration',['../class_microsoft_1_1_psi_1_1_microsoft_speech_1_1_microsoft_speech_recognizer_configuration.html',1,'Microsoft::Psi::MicrosoftSpeech']]],
  ['modeinfo_3305',['ModeInfo',['../class_microsoft_1_1_psi_1_1_device_management_1_1_camera_device_info_1_1_sensor_1_1_mode_info.html',1,'Microsoft::Psi::DeviceManagement::CameraDeviceInfo::Sensor']]],
  ['modelvisual3dvisualizationobject_3306',['ModelVisual3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_model_visual3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['modelvisual3dvisualizationobject_3c_20coordinatesystem_20_3e_3307',['ModelVisual3DVisualizationObject&lt; CoordinateSystem &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_model_visual3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['modelvisual3dvisualizationobject_3c_20rect3d_20_3e_3308',['ModelVisual3DVisualizationObject&lt; Rect3D &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_model_visual3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['modelvisual3dvisualizationobjectcollectionbase_3309',['ModelVisual3DVisualizationObjectCollectionBase',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_model_visual3_d_visualization_object_collection_base.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['modelvisual3dvisualizationobjectcollectionbase_3c_20tvisobj_2c_20tcoll_20_3e_3310',['ModelVisual3DVisualizationObjectCollectionBase&lt; TVisObj, TColl &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_model_visual3_d_visualization_object_collection_base.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['modelvisual3dvisualizationobjectenumerable_3311',['ModelVisual3DVisualizationObjectEnumerable',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_model_visual3_d_visualization_object_enumerable.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['mp4writer_3312',['MP4Writer',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_m_p4_writer.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mp4writerconfiguration_3313',['MP4WriterConfiguration',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_m_p4_writer_configuration.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mp4writerunmanageddata_3314',['MP4WriterUnmanagedData',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_m_p4_writer_unmanaged_data.html',1,'Microsoft::Psi::Media_Interop']]],
  ['mpeg4writer_3315',['Mpeg4Writer',['../class_microsoft_1_1_psi_1_1_media_1_1_mpeg4_writer.html',1,'Microsoft::Psi::Media']]],
  ['mpeg4writerconfiguration_3316',['Mpeg4WriterConfiguration',['../class_microsoft_1_1_psi_1_1_media_1_1_mpeg4_writer_configuration.html',1,'Microsoft::Psi::Media']]],
  ['multicameracalibration_3317',['MultiCameraCalibration',['../class_microsoft_1_1_psi_1_1_calibration_1_1_multi_camera_calibration.html',1,'Microsoft::Psi::Calibration']]]
];
