var searchData=
[
  ['i3dvisualizationobject',['I3DVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['ibitmapencoder',['IBitmapEncoder',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_i_bitmap_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['icameraintrinsics',['ICameraIntrinsics',['../interface_microsoft_1_1_psi_1_1_calibration_1_1_i_camera_intrinsics.html',1,'Microsoft::Psi::Calibration']]],
  ['iclassfactory',['IClassFactory',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_server_1_1_i_class_factory.html',1,'Microsoft::Psi::Visualization::Server']]],
  ['iconsumer',['IConsumer',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20audiobuffer_20_3e',['IConsumer&lt; AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20t_20_3e',['IConsumer&lt; T &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20tclock_20_3e',['IConsumer&lt; TClock &gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumer_3c_20tin_5b_5d_3e',['IConsumer&lt; TIn[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_consumer.html',1,'Microsoft::Psi']]],
  ['iconsumerproducer',['IConsumerProducer',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['iconsumerproducer_3c_20audiobuffer_2c_20bool_20_3e',['IConsumerProducer&lt; AudioBuffer, bool &gt;',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_consumer_producer.html',1,'Microsoft::Psi::Components']]],
  ['icontext',['IContext',['../interface_microsoft_1_1_psi_1_1_finite_state_machine_1_1_i_context.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['iemitter',['IEmitter',['../interface_microsoft_1_1_psi_1_1_i_emitter.html',1,'Microsoft::Psi']]],
  ['ifinitesourcecomponent',['IFiniteSourceComponent',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_finite_source_component.html',1,'Microsoft::Psi::Components']]],
  ['iimagecompressor',['IImageCompressor',['../interface_microsoft_1_1_psi_1_1_imaging_1_1_image_1_1_i_image_compressor.html',1,'Microsoft::Psi::Imaging::Image']]],
  ['iindexer',['IIndexer',['../interface_microsoft_1_1_psi_1_1_arrays_1_1_i_indexer.html',1,'Microsoft::Psi::Arrays']]],
  ['iinterval',['IInterval',['../interface_microsoft_1_1_psi_1_1_i_interval.html',1,'Microsoft::Psi']]],
  ['iintervalendpoint',['IIntervalEndpoint',['../interface_microsoft_1_1_psi_1_1_i_interval_endpoint.html',1,'Microsoft::Psi']]],
  ['ikinectcalibration',['IKinectCalibration',['../interface_microsoft_1_1_psi_1_1_kinect_1_1_i_kinect_calibration.html',1,'Microsoft::Psi::Kinect']]],
  ['ikinectfacedetector',['IKinectFaceDetector',['../interface_microsoft_1_1_psi_1_1_kinect_1_1_face_1_1_i_kinect_face_detector.html',1,'Microsoft::Psi::Kinect::Face']]],
  ['ikinectsensor',['IKinectSensor',['../interface_microsoft_1_1_psi_1_1_kinect_1_1_i_kinect_sensor.html',1,'Microsoft::Psi::Kinect']]],
  ['image',['Image',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image.html',1,'Microsoft::Psi::Imaging']]],
  ['imageanalyzer',['ImageAnalyzer',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_vision_1_1_image_analyzer.html',1,'Microsoft::Psi::CognitiveServices::Vision']]],
  ['imageanalyzerconfiguration',['ImageAnalyzerConfiguration',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_vision_1_1_image_analyzer_configuration.html',1,'Microsoft::Psi::CognitiveServices::Vision']]],
  ['imagecompressor',['ImageCompressor',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_compressor.html',1,'Microsoft::Psi::Imaging']]],
  ['imagedecoder',['ImageDecoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_decoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imageencoder',['ImageEncoder',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_encoder.html',1,'Microsoft::Psi::Imaging']]],
  ['imageframe',['ImageFrame',['../class_microsoft_1_1_psi_1_1_media_1_1_media_capture_internal_1_1_image_frame.html',1,'Microsoft::Psi::Media::MediaCaptureInternal']]],
  ['imagepool',['ImagePool',['../class_microsoft_1_1_psi_1_1_imaging_1_1_image_pool.html',1,'Microsoft::Psi::Imaging']]],
  ['imagevisualizationobject',['ImageVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_client_1_1_image_visualization_object.html',1,'Microsoft::Psi::Visualization::Client']]],
  ['imagevisualizationobjectbase',['ImageVisualizationObjectBase',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_image_visualization_object_base.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['imagevisualizationobjectbaseconfiguration',['ImageVisualizationObjectBaseConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_image_visualization_object_base_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['imagingoperators',['ImagingOperators',['../class_microsoft_1_1_psi_1_1_imaging_1_1_imaging_operators.html',1,'Microsoft::Psi::Imaging']]],
  ['imediacapture',['IMediaCapture',['../interface_microsoft_1_1_psi_1_1_media_1_1_i_media_capture.html',1,'Microsoft::Psi::Media']]],
  ['importer',['Importer',['../class_microsoft_1_1_psi_1_1_data_1_1_importer.html',1,'Microsoft::Psi::Data']]],
  ['indexdefinition',['IndexDefinition',['../class_microsoft_1_1_psi_1_1_arrays_1_1_index_definition.html',1,'Microsoft::Psi::Arrays']]],
  ['indexentry',['IndexEntry',['../struct_microsoft_1_1_psi_1_1_persistence_1_1_index_entry.html',1,'Microsoft::Psi::Persistence']]],
  ['indexer',['Indexer',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer.html',1,'Microsoft::Psi::Arrays']]],
  ['indexer2d',['Indexer2d',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer2d.html',1,'Microsoft::Psi::Arrays']]],
  ['indexernd',['IndexerNd',['../class_microsoft_1_1_psi_1_1_arrays_1_1_indexer_nd.html',1,'Microsoft::Psi::Arrays']]],
  ['instant3dvisualizationobject',['Instant3DVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant3_d_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instant3dvisualizationobjectconfiguration',['Instant3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_instant3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['instant3dvisualizationobjectcontractresolver',['Instant3DVisualizationObjectContractResolver',['../class_microsoft_1_1_psi_1_1_visualization_1_1_serialization_1_1_instant3_d_visualization_object_contract_resolver.html',1,'Microsoft::Psi::Visualization::Serialization']]],
  ['instantvisualizationobject',['InstantVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instantvisualizationobject_3c_20tdata_2c_20imagevisualizationobjectbaseconfiguration_20_3e',['InstantVisualizationObject&lt; TData, ImageVisualizationObjectBaseConfiguration &gt;',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_instant_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['instantvisualizationobjectconfiguration',['InstantVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_instant_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['intent',['Intent',['../class_microsoft_1_1_psi_1_1_language_1_1_intent.html',1,'Microsoft::Psi::Language']]],
  ['intentdata',['IntentData',['../class_microsoft_1_1_psi_1_1_language_1_1_intent_data.html',1,'Microsoft::Psi::Language']]],
  ['interpolator',['Interpolator',['../class_microsoft_1_1_psi_1_1_match_1_1_interpolator.html',1,'Microsoft::Psi::Match']]],
  ['interval',['Interval',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20datetime_2c_20timespan_2c_20intervalendpoint_3c_20datetime_20_3e_2c_20timeinterval_20_3e',['Interval&lt; DateTime, TimeSpan, IntervalEndpoint&lt; DateTime &gt;, TimeInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20double_2c_20double_2c_20intervalendpoint_3c_20double_20_3e_2c_20realinterval_20_3e',['Interval&lt; double, double, IntervalEndpoint&lt; double &gt;, RealInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20int_2c_20int_2c_20intervalendpoint_3c_20int_20_3e_2c_20intinterval_20_3e',['Interval&lt; int, int, IntervalEndpoint&lt; int &gt;, IntInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['interval_3c_20timespan_2c_20timespan_2c_20intervalendpoint_3c_20timespan_20_3e_2c_20relativetimeinterval_20_3e',['Interval&lt; TimeSpan, TimeSpan, IntervalEndpoint&lt; TimeSpan &gt;, RelativeTimeInterval &gt;',['../class_microsoft_1_1_psi_1_1_interval.html',1,'Microsoft::Psi']]],
  ['intervaldata',['IntervalData',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_interval_data.html',1,'Microsoft.Psi.Visualization.Data.IntervalData'],['../struct_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_interval_data.html',1,'Microsoft.Psi.Visualization.Data.IntervalData&lt; T &gt;']]],
  ['intervalendpoint',['IntervalEndpoint',['../class_microsoft_1_1_psi_1_1_interval_endpoint.html',1,'Microsoft::Psi']]],
  ['intinterval',['IntInterval',['../class_microsoft_1_1_psi_1_1_int_interval.html',1,'Microsoft::Psi']]],
  ['ipartition',['IPartition',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_partition.html',1,'Microsoft::Psi::Data']]],
  ['iperfcountercollection',['IPerfCounterCollection',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20emittercounters_20_3e',['IPerfCounterCollection&lt; EmitterCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20priorityqueuecounters_20_3e',['IPerfCounterCollection&lt; PriorityQueueCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20receivercounters_20_3e',['IPerfCounterCollection&lt; ReceiverCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcountercollection_3c_20schedulercounters_20_3e',['IPerfCounterCollection&lt; SchedulerCounters &gt;',['../interface_microsoft_1_1_psi_1_1_i_perf_counter_collection.html',1,'Microsoft::Psi']]],
  ['iperfcounters',['IPerfCounters',['../interface_microsoft_1_1_psi_1_1_i_perf_counters.html',1,'Microsoft::Psi']]],
  ['ipool',['IPool',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_pool.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['iproducer',['IProducer',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20audiobuffer_20_3e',['IProducer&lt; AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20microsoft_2epsi_2eaudio_2emicrosoft_3a_3apsi_3a_3aaudio_3a_3aaudiobuffer_20_3e',['IProducer&lt; Microsoft.Psi.Audio.Microsoft::Psi::Audio::AudioBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20t_20_3e',['IProducer&lt; T &gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['iproducer_3c_20tout_5b_5d_3e',['IProducer&lt; TOut[]&gt;',['../interface_microsoft_1_1_psi_1_1_i_producer.html',1,'Microsoft::Psi']]],
  ['irealsensedeviceunmanaged',['IRealSenseDeviceUnmanaged',['../struct_i_real_sense_device_unmanaged.html',1,'']]],
  ['ireceiver',['IReceiver',['../interface_microsoft_1_1_psi_1_1_i_receiver.html',1,'Microsoft::Psi']]],
  ['irecyclingpool',['IRecyclingPool',['../interface_microsoft_1_1_psi_1_1_i_recycling_pool.html',1,'Microsoft::Psi']]],
  ['irecyclingpool_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20tinput_20_3e_20_3e',['IRecyclingPool&lt; Microsoft::Psi::Message&lt; TInput &gt; &gt;',['../interface_microsoft_1_1_psi_1_1_i_recycling_pool.html',1,'Microsoft::Psi']]],
  ['iserializer',['ISerializer',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20bufferreader_20_3e',['ISerializer&lt; BufferReader &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20byte_5b_5d_3e',['ISerializer&lt; byte[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20image_20_3e',['ISerializer&lt; Image &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20string_20_3e',['ISerializer&lt; string &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20string_5b_5d_3e',['ISerializer&lt; string[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20t_5b_5d_3e',['ISerializer&lt; T[]&gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['iserializer_3c_20unmanagedbuffer_20_3e',['ISerializer&lt; UnmanagedBuffer &gt;',['../interface_microsoft_1_1_psi_1_1_serialization_1_1_i_serializer.html',1,'Microsoft::Psi::Serialization']]],
  ['isimplereader',['ISimpleReader',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_simple_reader.html',1,'Microsoft::Psi::Data']]],
  ['isimplewriter',['ISimpleWriter',['../interface_microsoft_1_1_psi_1_1_data_1_1_i_simple_writer.html',1,'Microsoft::Psi::Data']]],
  ['isourcecomponent',['ISourceComponent',['../interface_microsoft_1_1_psi_1_1_components_1_1_i_source_component.html',1,'Microsoft::Psi::Components']]],
  ['ispeechrecognitionalternate',['ISpeechRecognitionAlternate',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_speech_recognition_alternate.html',1,'Microsoft::Psi::Speech']]],
  ['ispeechrecognitionresult',['ISpeechRecognitionResult',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['istreamadapter',['IStreamAdapter',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamingspeechrecognitionresult',['IStreamingSpeechRecognitionResult',['../interface_microsoft_1_1_psi_1_1_speech_1_1_i_streaming_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['istreammetadata',['IStreamMetadata',['../interface_microsoft_1_1_psi_1_1_i_stream_metadata.html',1,'Microsoft::Psi']]],
  ['istreamreader',['IStreamReader',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_reader.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamsummary',['IStreamSummary',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_stream_summary.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['istreamtreenode',['IStreamTreeNode',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_datasets_1_1_i_stream_tree_node.html',1,'Microsoft::Psi::Visualization::Datasets']]],
  ['istreamvisualizationobject',['IStreamVisualizationObject',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_i_stream_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['isummarizer',['ISummarizer',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft.Psi.Visualization.Data.ISummarizer'],['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft.Psi.Visualization.Data.ISummarizer&lt; TSrc, TDest &gt;']]],
  ['isummarizer_3c_20tsrc_2c_20tdest_20_3e',['ISummarizer&lt; TSrc, TDest &gt;',['../interface_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_i_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]]
];
