var searchData=
[
  ['sampler',['Sampler',['../class_microsoft_1_1_psi_1_1_components_1_1_sampler.html',1,'Microsoft::Psi::Components']]],
  ['scattercoordinatesystemsvisualizationobjectconfiguration',['ScatterCoordinateSystemsVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_scatter_coordinate_systems_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['scatterline3dvisualizationobjectconfiguration',['ScatterLine3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_scatter_line3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['scatterplanardirectionvisualizationobjectconfiguration',['ScatterPlanarDirectionVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_scatter_planar_direction_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['scatterplotvisualizationobjectconfiguration',['ScatterPlotVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_scatter_plot_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['scatterrect3dvisualizationobjectconfiguration',['ScatterRect3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_scatter_rect3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['scatterrectanglevisualizationobjectconfiguration',['ScatterRectangleVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_scatter_rectangle_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['scheduler',['Scheduler',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_scheduler.html',1,'Microsoft::Psi::Scheduling']]],
  ['serializationcontext',['SerializationContext',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_context.html',1,'Microsoft::Psi::Serialization']]],
  ['serializationhandler',['SerializationHandler',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft.Psi.Serialization.SerializationHandler'],['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft.Psi.Serialization.SerializationHandler&lt; T &gt;']]],
  ['serializationhandler_3c_20sharedcontainer_3c_20t_20_3e_20_3e',['SerializationHandler&lt; SharedContainer&lt; T &gt; &gt;',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft::Psi::Serialization']]],
  ['serializationhandler_3c_20t_20_3e',['SerializationHandler&lt; T &gt;',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serialization_handler.html',1,'Microsoft::Psi::Serialization']]],
  ['serializer',['Serializer',['../class_microsoft_1_1_psi_1_1_serializer.html',1,'Microsoft::Psi']]],
  ['serializerattribute',['SerializerAttribute',['../class_microsoft_1_1_psi_1_1_serialization_1_1_serializer_attribute.html',1,'Microsoft::Psi::Serialization']]],
  ['serializercomponent',['SerializerComponent',['../class_microsoft_1_1_psi_1_1_components_1_1_serializer_component.html',1,'Microsoft::Psi::Components']]],
  ['session',['Session',['../class_microsoft_1_1_psi_1_1_data_1_1_session.html',1,'Microsoft::Psi::Data']]],
  ['sessionimporter',['SessionImporter',['../class_microsoft_1_1_psi_1_1_data_1_1_session_importer.html',1,'Microsoft::Psi::Data']]],
  ['shared',['Shared',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft.Psi.Shared'],['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft.Psi.Shared&lt; T &gt;']]],
  ['shared_3c_20metadatacache_20_3e',['Shared&lt; MetadataCache &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['shared_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aimage_20_3e',['Shared&lt; Microsoft::Psi::Imaging::Image &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['shared_3c_20pageindexcache_20_3e',['Shared&lt; PageIndexCache &gt;',['../class_microsoft_1_1_psi_1_1_shared.html',1,'Microsoft::Psi']]],
  ['sharedarraypool',['SharedArrayPool',['../class_microsoft_1_1_psi_1_1_shared_array_pool.html',1,'Microsoft::Psi']]],
  ['sharedpool',['SharedPool',['../class_microsoft_1_1_psi_1_1_shared_pool.html',1,'Microsoft::Psi']]],
  ['sharedpool_3c_20microsoft_3a_3apsi_3a_3aimaging_3a_3aencodedimage_20_3e',['SharedPool&lt; Microsoft::Psi::Imaging::EncodedImage &gt;',['../class_microsoft_1_1_psi_1_1_shared_pool.html',1,'Microsoft::Psi']]],
  ['simpleconsumer',['SimpleConsumer',['../class_microsoft_1_1_psi_1_1_components_1_1_simple_consumer.html',1,'Microsoft::Psi::Components']]],
  ['simpleconsumer_3c_20audiobuffer_20_3e',['SimpleConsumer&lt; AudioBuffer &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_simple_consumer.html',1,'Microsoft::Psi::Components']]],
  ['simplereader',['SimpleReader',['../class_microsoft_1_1_psi_1_1_data_1_1_simple_reader.html',1,'Microsoft::Psi::Data']]],
  ['simplesemaphore',['SimpleSemaphore',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_simple_semaphore.html',1,'Microsoft::Psi::Scheduling']]],
  ['simplevoiceactivitydetector',['SimpleVoiceActivityDetector',['../class_microsoft_1_1_psi_1_1_speech_1_1_simple_voice_activity_detector.html',1,'Microsoft::Psi::Speech']]],
  ['simplevoiceactivitydetectorconfiguration',['SimpleVoiceActivityDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_simple_voice_activity_detector_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['solvedboard',['SolvedBoard',['../class_microsoft_1_1_psi_1_1_calibration_1_1_system_calibration_1_1_solved_board.html',1,'Microsoft::Psi::Calibration::SystemCalibration']]],
  ['sourcereadercallback',['SourceReaderCallback',['../class_microsoft_1_1_psi_1_1_media___interop_1_1_source_reader_callback.html',1,'Microsoft::Psi::Media_Interop']]],
  ['speakcompletedeventdata',['SpeakCompletedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_speak_completed_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['speakprogresseventdata',['SpeakProgressEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_speak_progress_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['speakstartedeventdata',['SpeakStartedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_speak_started_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['specific',['Specific',['../class_microsoft_1_1_psi_1_1_platform_1_1_specific.html',1,'Microsoft::Psi::Platform']]],
  ['spectralentropy',['SpectralEntropy',['../class_microsoft_1_1_psi_1_1_audio_1_1_spectral_entropy.html',1,'Microsoft::Psi::Audio']]],
  ['speecherroreventargs',['SpeechErrorEventArgs',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_speech_error_event_args.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['speechrecognitionalternate',['SpeechRecognitionAlternate',['../class_microsoft_1_1_psi_1_1_speech_1_1_speech_recognition_alternate.html',1,'Microsoft::Psi::Speech']]],
  ['speechrecognitionclient',['SpeechRecognitionClient',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_speech_recognition_client.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['speechrecognitionresult',['SpeechRecognitionResult',['../class_microsoft_1_1_psi_1_1_speech_1_1_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['speechrecognitionvisualizationobjectconfiguration',['SpeechRecognitionVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_speech_recognition_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['speechresponseeventargs',['SpeechResponseEventArgs',['../class_microsoft_1_1_psi_1_1_cognitive_services_1_1_speech_1_1_service_1_1_speech_response_event_args.html',1,'Microsoft::Psi::CognitiveServices::Speech::Service']]],
  ['splitter',['Splitter',['../class_microsoft_1_1_psi_1_1_components_1_1_splitter.html',1,'Microsoft::Psi::Components']]],
  ['splitter_3c_20microsoft_3a_3apsi_3a_3amessage_3c_20microsoft_3a_3apsi_3a_3acommon_3a_3abufferreader_20_3e_2c_20int_20_3e',['Splitter&lt; Microsoft::Psi::Message&lt; Microsoft::Psi::Common::BufferReader &gt;, int &gt;',['../class_microsoft_1_1_psi_1_1_components_1_1_splitter.html',1,'Microsoft::Psi::Components']]],
  ['sprite3dvisualizationobjectconfiguration',['Sprite3DVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_sprite3_d_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['state',['State',['../class_microsoft_1_1_psi_1_1_finite_state_machine_1_1_state.html',1,'Microsoft::Psi::FiniteStateMachine']]],
  ['statechangedeventdata',['StateChangedEventData',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_1_1_state_changed_event_data.html',1,'Microsoft::Psi::Speech::SystemSpeechSynthesizer']]],
  ['store',['Store',['../class_microsoft_1_1_psi_1_1_store.html',1,'Microsoft::Psi']]],
  ['storepartition',['StorePartition',['../class_microsoft_1_1_psi_1_1_data_1_1_store_partition.html',1,'Microsoft::Psi::Data']]],
  ['storereader',['StoreReader',['../class_microsoft_1_1_psi_1_1_persistence_1_1_store_reader.html',1,'Microsoft::Psi::Persistence']]],
  ['storewriter',['StoreWriter',['../class_microsoft_1_1_psi_1_1_persistence_1_1_store_writer.html',1,'Microsoft::Psi::Persistence']]],
  ['streamadapter',['StreamAdapter',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_adapter.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streambinding',['StreamBinding',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_binding.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamenumerable',['StreamEnumerable',['../class_microsoft_1_1_psi_1_1_operators_1_1_stream_enumerable.html',1,'Microsoft::Psi::Operators']]],
  ['streamingspeechrecognitionresult',['StreamingSpeechRecognitionResult',['../class_microsoft_1_1_psi_1_1_speech_1_1_streaming_speech_recognition_result.html',1,'Microsoft::Psi::Speech']]],
  ['streamobservable',['StreamObservable',['../class_microsoft_1_1_psi_1_1_operators_1_1_stream_observable.html',1,'Microsoft::Psi::Operators']]],
  ['streamreader',['StreamReader',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_reader.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamsummary',['StreamSummary',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_summary.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamsummarymanager',['StreamSummaryManager',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_stream_summary_manager.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['streamvisualizationobject',['StreamVisualizationObject',['../class_microsoft_1_1_psi_1_1_visualization_1_1_visualization_objects_1_1_stream_visualization_object.html',1,'Microsoft::Psi::Visualization::VisualizationObjects']]],
  ['streamvisualizationobjectconfiguration',['StreamVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_stream_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['stringwithdurationvisualizationobjectconfiguration',['StringWithDurationVisualizationObjectConfiguration',['../class_microsoft_1_1_psi_1_1_visualization_1_1_config_1_1_string_with_duration_visualization_object_configuration.html',1,'Microsoft::Psi::Visualization::Config']]],
  ['subpipeline',['Subpipeline',['../class_microsoft_1_1_psi_1_1_subpipeline.html',1,'Microsoft::Psi']]],
  ['summarizer',['Summarizer',['../class_microsoft_1_1_psi_1_1_visualization_1_1_data_1_1_summarizer.html',1,'Microsoft::Psi::Visualization::Data']]],
  ['synchronizationlock',['SynchronizationLock',['../class_microsoft_1_1_psi_1_1_scheduling_1_1_synchronization_lock.html',1,'Microsoft::Psi::Scheduling']]],
  ['systemcalibration',['SystemCalibration',['../class_microsoft_1_1_psi_1_1_calibration_1_1_system_calibration.html',1,'Microsoft::Psi::Calibration']]],
  ['systemspeech',['SystemSpeech',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechintentdetector',['SystemSpeechIntentDetector',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_intent_detector.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechintentdetectorconfiguration',['SystemSpeechIntentDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_intent_detector_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechrecognizer',['SystemSpeechRecognizer',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_recognizer.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechrecognizerconfiguration',['SystemSpeechRecognizerConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_recognizer_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechsynthesizer',['SystemSpeechSynthesizer',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer.html',1,'Microsoft::Psi::Speech']]],
  ['systemspeechsynthesizerconfiguration',['SystemSpeechSynthesizerConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_speech_synthesizer_configuration.html',1,'Microsoft::Psi::Speech']]],
  ['systemvoiceactivitydetector',['SystemVoiceActivityDetector',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_voice_activity_detector.html',1,'Microsoft::Psi::Speech']]],
  ['systemvoiceactivitydetectorconfiguration',['SystemVoiceActivityDetectorConfiguration',['../class_microsoft_1_1_psi_1_1_speech_1_1_system_voice_activity_detector_configuration.html',1,'Microsoft::Psi::Speech']]]
];
